-- ============================================
-- V2.3 캘린더/이벤트 테이블 마이그레이션
-- 적용 대상: 기존 운영 DB
-- 작성일: 2025-01-18
-- ============================================

-- ============================================
-- 1. TB_CALENDAR (캘린더/이벤트 그룹)
-- ============================================
CREATE TABLE IF NOT EXISTS TB_CALENDAR (
    CALENDAR_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '캘린더 ID',
    OWNER_USERNAME VARCHAR(50) NOT NULL COMMENT '소유자 USERNAME',
    CALENDAR_NAME VARCHAR(100) NOT NULL COMMENT '캘린더 이름',
    DESCRIPTION VARCHAR(500) NULL COMMENT '설명',
    COLOR VARCHAR(20) NOT NULL DEFAULT '#3b82f6' COMMENT '색상 (HEX)',
    IS_DEFAULT BOOLEAN NOT NULL DEFAULT FALSE COMMENT '기본 캘린더 여부',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자',
    PRIMARY KEY (CALENDAR_ID),
    INDEX IDX_CALENDAR_OWNER (OWNER_USERNAME),
    INDEX IDX_CALENDAR_DEFAULT (OWNER_USERNAME, IS_DEFAULT),
    CONSTRAINT FK_CALENDAR_OWNER FOREIGN KEY (OWNER_USERNAME) REFERENCES TB_USER(USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='캘린더(이벤트 그룹)';

-- ============================================
-- 2. TB_CALENDAR_SHARE (캘린더 공유)
-- ============================================
CREATE TABLE IF NOT EXISTS TB_CALENDAR_SHARE (
    CALENDAR_SHARE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '공유 ID',
    CALENDAR_ID BIGINT NOT NULL COMMENT '캘린더 ID',
    SHARE_TYPE VARCHAR(20) NOT NULL COMMENT '공유 유형 (VIEW, EDIT)',
    USERNAME VARCHAR(50) NOT NULL COMMENT '공유받은 사용자',
    SHARED_BY VARCHAR(50) NOT NULL COMMENT '공유한 사용자',
    SHARED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '공유일시',
    DELETED_AT DATETIME NULL COMMENT '해제일시',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자',
    PRIMARY KEY (CALENDAR_SHARE_ID),
    UNIQUE KEY UK_CALENDAR_SHARE (CALENDAR_ID, USERNAME, DELETED_AT),
    INDEX IDX_CALENDAR_SHARE_USER (USERNAME),
    CONSTRAINT FK_CALENDAR_SHARE_CALENDAR FOREIGN KEY (CALENDAR_ID) REFERENCES TB_CALENDAR(CALENDAR_ID),
    CONSTRAINT FK_CALENDAR_SHARE_USER FOREIGN KEY (USERNAME) REFERENCES TB_USER(USERNAME),
    CONSTRAINT FK_CALENDAR_SHARE_BY FOREIGN KEY (SHARED_BY) REFERENCES TB_USER(USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='캘린더 공유';

-- ============================================
-- 3. TB_EVENT (이벤트)
-- ============================================
CREATE TABLE IF NOT EXISTS TB_EVENT (
    EVENT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '이벤트 ID',
    CALENDAR_ID BIGINT NOT NULL COMMENT '캘린더 ID',
    OWNER_USERNAME VARCHAR(50) NOT NULL COMMENT '소유자 USERNAME',
    TITLE VARCHAR(200) NOT NULL COMMENT '제목',
    DESCRIPTION TEXT NULL COMMENT '설명',
    LOCATION VARCHAR(200) NULL COMMENT '장소',
    START_DATE DATE NOT NULL COMMENT '시작일 (양력)',
    END_DATE DATE NOT NULL COMMENT '종료일 (양력)',
    START_TIME TIME NULL COMMENT '시작 시간',
    END_TIME TIME NULL COMMENT '종료 시간',
    IS_ALL_DAY BOOLEAN NOT NULL DEFAULT TRUE COMMENT '종일 이벤트 여부',
    -- 음력 관련
    IS_LUNAR BOOLEAN NOT NULL DEFAULT FALSE COMMENT '음력 이벤트 여부',
    LUNAR_MONTH INT NULL COMMENT '음력 월',
    LUNAR_DAY INT NULL COMMENT '음력 일',
    LUNAR_LEAP_MONTH BOOLEAN NULL DEFAULT FALSE COMMENT '윤달 여부',
    -- 반복 관련
    IS_RECURRING BOOLEAN NOT NULL DEFAULT FALSE COMMENT '반복 이벤트 여부',
    RECURRENCE_TYPE VARCHAR(20) NULL COMMENT '반복 유형 (DAILY, WEEKLY, MONTHLY, YEARLY, MONTHLY_LUNAR, YEARLY_LUNAR)',
    RECURRENCE_INTERVAL INT NULL DEFAULT 1 COMMENT '반복 간격',
    RECURRENCE_END_DATE DATE NULL COMMENT '반복 종료일',
    RECURRENCE_COUNT INT NULL COMMENT '반복 횟수',
    RECURRENCE_DAYS VARCHAR(20) NULL COMMENT '반복 요일 (예: MON,WED,FRI)',
    PARENT_EVENT_ID BIGINT NULL COMMENT '원본 반복 이벤트 ID',
    EXCEPTION_DATES TEXT NULL COMMENT '예외 날짜 목록 (JSON)',
    -- 상태
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '상태 (ACTIVE, DELETED)',
    DELETED_AT DATETIME NULL COMMENT '삭제일시',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자',
    PRIMARY KEY (EVENT_ID),
    INDEX IDX_EVENT_CALENDAR (CALENDAR_ID),
    INDEX IDX_EVENT_OWNER (OWNER_USERNAME),
    INDEX IDX_EVENT_DATE (START_DATE, END_DATE),
    INDEX IDX_EVENT_STATUS (STATUS),
    INDEX IDX_EVENT_RECURRING (IS_RECURRING, PARENT_EVENT_ID),
    CONSTRAINT FK_EVENT_CALENDAR FOREIGN KEY (CALENDAR_ID) REFERENCES TB_CALENDAR(CALENDAR_ID),
    CONSTRAINT FK_EVENT_OWNER FOREIGN KEY (OWNER_USERNAME) REFERENCES TB_USER(USERNAME),
    CONSTRAINT FK_EVENT_PARENT FOREIGN KEY (PARENT_EVENT_ID) REFERENCES TB_EVENT(EVENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='이벤트';

-- ============================================
-- 4. TB_EVENT_SHARE (이벤트 공유)
-- ============================================
CREATE TABLE IF NOT EXISTS TB_EVENT_SHARE (
    EVENT_SHARE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '공유 ID',
    EVENT_ID BIGINT NOT NULL COMMENT '이벤트 ID',
    SHARE_TYPE VARCHAR(20) NOT NULL COMMENT '공유 유형 (VIEW, EDIT, TRANSFER)',
    USERNAME VARCHAR(50) NOT NULL COMMENT '공유받은 사용자',
    SHARED_BY VARCHAR(50) NOT NULL COMMENT '공유한 사용자',
    SHARED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '공유일시',
    DELETED_AT DATETIME NULL COMMENT '해제일시',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자',
    PRIMARY KEY (EVENT_SHARE_ID),
    UNIQUE KEY UK_EVENT_SHARE (EVENT_ID, USERNAME, DELETED_AT),
    INDEX IDX_EVENT_SHARE_USER (USERNAME),
    CONSTRAINT FK_EVENT_SHARE_EVENT FOREIGN KEY (EVENT_ID) REFERENCES TB_EVENT(EVENT_ID),
    CONSTRAINT FK_EVENT_SHARE_USER FOREIGN KEY (USERNAME) REFERENCES TB_USER(USERNAME),
    CONSTRAINT FK_EVENT_SHARE_BY FOREIGN KEY (SHARED_BY) REFERENCES TB_USER(USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='이벤트 공유';

-- ============================================
-- 5. 기존 사용자에게 기본 캘린더 생성
-- ============================================
INSERT INTO TB_CALENDAR (OWNER_USERNAME, CALENDAR_NAME, DESCRIPTION, COLOR, IS_DEFAULT, SORT_ORDER, CREATED_BY)
SELECT
    u.USERNAME,
    '기본',
    '기본 캘린더',
    '#3b82f6',
    TRUE,
    0,
    u.USERNAME
FROM TB_USER u
WHERE u.USE_YN = 'Y'
  AND NOT EXISTS (
      SELECT 1 FROM TB_CALENDAR c
      WHERE c.OWNER_USERNAME = u.USERNAME AND c.IS_DEFAULT = TRUE
  );

-- ============================================
-- 마이그레이션 완료 확인
-- ============================================
SELECT 'V2.3 Calendar/Event Tables Migration Completed' AS STATUS;
SELECT
    (SELECT COUNT(*) FROM TB_CALENDAR) AS CALENDAR_COUNT,
    (SELECT COUNT(*) FROM TB_EVENT) AS EVENT_COUNT,
    (SELECT COUNT(*) FROM TB_CALENDAR WHERE IS_DEFAULT = TRUE) AS DEFAULT_CALENDAR_COUNT;
