-- ============================================
-- V2.4 날짜 기준 테이블 마이그레이션
-- 적용 대상: 기존 운영 DB
-- 작성일: 2026-01-18
-- ============================================

-- =============================================
-- TB_CALENDAR_DATE (날짜 기준 테이블)
-- =============================================
CREATE TABLE IF NOT EXISTS TB_CALENDAR_DATE (
    CAL_DATE DATE NOT NULL COMMENT '양력 날짜 (PK)',

    -- 양력 정보
    SOLAR_YEAR SMALLINT NOT NULL COMMENT '양력 연도',
    SOLAR_MONTH TINYINT NOT NULL COMMENT '양력 월',
    SOLAR_DAY TINYINT NOT NULL COMMENT '양력 일',
    DAY_OF_WEEK TINYINT NOT NULL COMMENT '요일 (1=일, 2=월, ..., 7=토)',
    DAY_OF_WEEK_NAME VARCHAR(10) NOT NULL COMMENT '요일명 (일,월,화...)',
    WEEK_OF_YEAR TINYINT NOT NULL COMMENT '연중 주차',
    WEEK_OF_MONTH TINYINT NOT NULL COMMENT '월중 주차',
    QUARTER TINYINT NOT NULL COMMENT '분기 (1-4)',

    -- 음력 정보
    LUNAR_YEAR SMALLINT NOT NULL COMMENT '음력 연도',
    LUNAR_MONTH TINYINT NOT NULL COMMENT '음력 월',
    LUNAR_DAY TINYINT NOT NULL COMMENT '음력 일',
    IS_LEAP_MONTH BOOLEAN NOT NULL DEFAULT FALSE COMMENT '윤달 여부',
    LUNAR_DISPLAY VARCHAR(10) NOT NULL COMMENT '음력 표시 (12.5 or 윤4.1)',

    -- 근무일/휴일 정보
    IS_HOLIDAY BOOLEAN NOT NULL DEFAULT FALSE COMMENT '공휴일 여부',
    HOLIDAY_NAME VARCHAR(50) NULL COMMENT '공휴일명',
    HOLIDAY_TYPE VARCHAR(20) NULL COMMENT '공휴일 유형 (SOLAR_FIXED, LUNAR_FIXED, SUBSTITUTE, TEMPORARY)',
    IS_WORKDAY BOOLEAN NOT NULL DEFAULT TRUE COMMENT '근무일 여부',

    -- 감사 필드
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',

    PRIMARY KEY (CAL_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='날짜 기준 테이블';

-- TB_CALENDAR_DATE 인덱스 (존재하지 않을 경우에만 생성)
CREATE INDEX IDX_CAL_YEAR_MONTH ON TB_CALENDAR_DATE (SOLAR_YEAR, SOLAR_MONTH);
CREATE INDEX IDX_CAL_LUNAR ON TB_CALENDAR_DATE (LUNAR_YEAR, LUNAR_MONTH, LUNAR_DAY);
CREATE INDEX IDX_CAL_WORKDAY ON TB_CALENDAR_DATE (CAL_DATE, IS_WORKDAY);
CREATE INDEX IDX_CAL_HOLIDAY ON TB_CALENDAR_DATE (IS_HOLIDAY, CAL_DATE);

-- ============================================
-- 마이그레이션 완료 확인
-- ============================================
SELECT 'V2.4 Calendar Date Table Migration Completed' AS STATUS;
SELECT COUNT(*) AS EXISTING_RECORDS FROM TB_CALENDAR_DATE;
