-- ============================================
-- TaskFlow Database Schema v2.0
-- USERNAME/DEPARTMENT_CODE 기반 참조
-- MySQL 8.0+
-- ============================================

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

-- ============================================
-- 1. TB_DEPARTMENT - 부서 (Shadow)
-- ============================================
CREATE TABLE TB_DEPARTMENT (
    DEPARTMENT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '부서 ID (내부용)',
    DEPARTMENT_CODE VARCHAR(20) NOT NULL COMMENT '부서 코드 (FK 참조 키)',
    DEPARTMENT_NAME VARCHAR(100) NOT NULL COMMENT '부서명',
    PARENT_CODE VARCHAR(20) NULL COMMENT '상위 부서 코드',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    LAST_SYNCED_AT DATETIME NULL COMMENT '마지막 동기화 시간',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (DEPARTMENT_ID),
    UNIQUE KEY UK_DEPT_CODE (DEPARTMENT_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='부서';

-- TB_DEPARTMENT 인덱스
CREATE INDEX IDX_DEPT_PARENT ON TB_DEPARTMENT (PARENT_CODE);
CREATE INDEX IDX_DEPT_USE ON TB_DEPARTMENT (USE_YN, SORT_ORDER);

-- ============================================
-- 2. TB_POSITION - 직급 (Shadow)
-- ============================================
CREATE TABLE TB_POSITION (
    POSITION_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '직급 ID (내부용)',
    POSITION_CODE VARCHAR(20) NOT NULL COMMENT '직급 코드 (FK 참조 키)',
    POSITION_NAME VARCHAR(50) NOT NULL COMMENT '직급명',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서 (낮을수록 높은 직급)',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    LAST_SYNCED_AT DATETIME NULL COMMENT '마지막 동기화 시간 (External)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (POSITION_ID),
    UNIQUE KEY UK_POSITION_CODE (POSITION_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='직급';

-- TB_POSITION 인덱스
CREATE INDEX IDX_POSITION_USE ON TB_POSITION (USE_YN, SORT_ORDER);

-- ============================================
-- 3. TB_USER - 사용자 (Shadow)
-- ============================================
CREATE TABLE TB_USER (
    USER_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '사용자 ID (JWT용)',
    USERNAME VARCHAR(50) NOT NULL COMMENT '로그인 ID (FK 참조 키)',
    PASSWORD VARCHAR(255) NULL COMMENT '비밀번호 (External 모드 NULL)',
    NAME VARCHAR(100) NOT NULL COMMENT '사용자 이름',
    EMAIL VARCHAR(100) NULL COMMENT '이메일',
    DEPARTMENT_CODE VARCHAR(20) NULL COMMENT '부서 코드',
    POSITION_CODE VARCHAR(20) NULL COMMENT '직급 코드',
    ROLE VARCHAR(20) NOT NULL DEFAULT 'USER' COMMENT '권한 (ADMIN, MANAGER, USER, GUEST)',
    HEAD_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '팀장 여부 (Y/N)',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    LAST_LOGIN_AT DATETIME NULL COMMENT '마지막 로그인',
    LAST_SYNCED_AT DATETIME NULL COMMENT '마지막 동기화 시간',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (USER_ID),
    UNIQUE KEY UK_USERNAME (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자';

-- TB_USER 인덱스
CREATE INDEX IDX_USER_DEPT ON TB_USER (DEPARTMENT_CODE);
CREATE INDEX IDX_USER_POSITION ON TB_USER (POSITION_CODE);
CREATE INDEX IDX_USER_HEAD ON TB_USER (DEPARTMENT_CODE, HEAD_YN);
CREATE INDEX IDX_USER_USE ON TB_USER (USE_YN);
CREATE INDEX IDX_USER_NAME ON TB_USER (NAME);

-- ============================================
-- 4. TB_GROUP - 그룹
-- ============================================
CREATE TABLE TB_GROUP (
    GROUP_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '그룹 ID',
    GROUP_CODE VARCHAR(20) NOT NULL COMMENT '그룹 코드',
    GROUP_NAME VARCHAR(100) NOT NULL COMMENT '그룹명',
    DESCRIPTION VARCHAR(500) NULL COMMENT '그룹 설명',
    GROUP_COLOR VARCHAR(7) NULL COMMENT '색상 (#RRGGBB)',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (GROUP_ID),
    UNIQUE KEY UK_GROUP_CODE (GROUP_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='그룹';

-- TB_GROUP 인덱스
CREATE INDEX IDX_GROUP_USE ON TB_GROUP (USE_YN, SORT_ORDER);

-- ============================================
-- 5. TB_USER_GROUP - 사용자-그룹 매핑
-- ============================================
CREATE TABLE TB_USER_GROUP (
    USER_GROUP_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '매핑 ID',
    USERNAME VARCHAR(50) NOT NULL COMMENT '사용자 USERNAME',
    GROUP_ID BIGINT NOT NULL COMMENT '그룹 ID',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (USER_GROUP_ID),
    UNIQUE KEY UK_USER_GROUP (USERNAME, GROUP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자-그룹 매핑';

-- TB_USER_GROUP 인덱스
CREATE INDEX IDX_UG_USER ON TB_USER_GROUP (USERNAME);
CREATE INDEX IDX_UG_GROUP ON TB_USER_GROUP (GROUP_ID);

-- ============================================
-- 6. TB_CATEGORY - 카테고리 (v2.0: 소유자 기반)
-- ============================================
CREATE TABLE TB_CATEGORY (
    CATEGORY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '카테고리 ID',
    CATEGORY_CODE VARCHAR(20) NOT NULL COMMENT '카테고리 코드',
    CATEGORY_NAME VARCHAR(100) NOT NULL COMMENT '카테고리명',
    DESCRIPTION VARCHAR(500) NULL COMMENT '카테고리 설명',
    CATEGORY_COLOR VARCHAR(20) NULL DEFAULT '#6B7280' COMMENT '색상',
    OWNER_USERNAME VARCHAR(50) NOT NULL COMMENT '소유자 USERNAME',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (CATEGORY_ID),
    UNIQUE KEY UK_CATEGORY_CODE (CATEGORY_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='카테고리';

-- TB_CATEGORY 인덱스
CREATE INDEX IDX_CATEGORY_SORT ON TB_CATEGORY (SORT_ORDER);
CREATE INDEX IDX_CATEGORY_USE ON TB_CATEGORY (USE_YN);
CREATE INDEX IDX_CATEGORY_OWNER ON TB_CATEGORY (OWNER_USERNAME);

-- ============================================
-- 6-1. TB_CATEGORY_SHARE - 카테고리 공유
-- ============================================
CREATE TABLE TB_CATEGORY_SHARE (
    SHARE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '공유 ID',
    CATEGORY_ID BIGINT NOT NULL COMMENT '카테고리 ID',
    SHARE_TYPE VARCHAR(20) NOT NULL COMMENT '공유 대상 유형 (USER/DEPARTMENT)',
    SHARE_TARGET VARCHAR(50) NOT NULL COMMENT '공유 대상 (USERNAME 또는 DEPARTMENT_CODE)',
    PERMISSION VARCHAR(20) NOT NULL DEFAULT 'READ' COMMENT '권한 (READ/WRITE)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (SHARE_ID),
    UNIQUE KEY UK_CATEGORY_SHARE (CATEGORY_ID, SHARE_TYPE, SHARE_TARGET)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='카테고리 공유';

-- TB_CATEGORY_SHARE 인덱스
CREATE INDEX IDX_CS_CATEGORY ON TB_CATEGORY_SHARE (CATEGORY_ID);
CREATE INDEX IDX_CS_TYPE_TARGET ON TB_CATEGORY_SHARE (SHARE_TYPE, SHARE_TARGET);

-- ============================================
-- 6-2. TB_CATEGORY_PROPERTY - 카테고리 속성 매핑 (v2.0: REQUIRED_YN 추가)
-- ============================================
CREATE TABLE TB_CATEGORY_PROPERTY (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '매핑 ID',
    CATEGORY_ID BIGINT NOT NULL COMMENT '카테고리 ID',
    PROPERTY_ID BIGINT NOT NULL COMMENT '속성 ID',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    DEFAULT_VALUE VARCHAR(500) NULL COMMENT '기본값',
    REQUIRED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '필수 여부 (카테고리 레벨)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_CATEGORY_PROPERTY (CATEGORY_ID, PROPERTY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='카테고리 속성 매핑';

-- TB_CATEGORY_PROPERTY 인덱스
CREATE INDEX IDX_CP_CATEGORY ON TB_CATEGORY_PROPERTY (CATEGORY_ID);
CREATE INDEX IDX_CP_PROPERTY ON TB_CATEGORY_PROPERTY (PROPERTY_ID);

-- ============================================
-- 6-3. TB_BOARD_CATEGORY - 보드-카테고리 매핑 (v2.0: DEFAULT_YN 추가)
-- ============================================
CREATE TABLE TB_BOARD_CATEGORY (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '매핑 ID',
    BOARD_ID BIGINT NOT NULL COMMENT '보드 ID',
    CATEGORY_ID BIGINT NOT NULL COMMENT '카테고리 ID',
    DEFAULT_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '기본 카테고리 여부',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_BOARD_CATEGORY (BOARD_ID, CATEGORY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='보드-카테고리 매핑';

-- TB_BOARD_CATEGORY 인덱스
CREATE INDEX IDX_BC_BOARD ON TB_BOARD_CATEGORY (BOARD_ID);
CREATE INDEX IDX_BC_CATEGORY ON TB_BOARD_CATEGORY (CATEGORY_ID);

-- ============================================
-- 6-4. TB_BOARD_PROPERTY - 보드 속성 설정 (v2.0 신규)
-- ============================================
CREATE TABLE TB_BOARD_PROPERTY (
    BOARD_PROPERTY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '보드 속성 ID',
    BOARD_ID BIGINT NOT NULL COMMENT '보드 ID',
    PROPERTY_ID BIGINT NOT NULL COMMENT '속성 ID',
    REQUIRED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '필수 여부 (보드 레벨 재설정)',
    VISIBLE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '표시 여부',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    DEFAULT_VALUE VARCHAR(500) NULL COMMENT '기본값',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (BOARD_PROPERTY_ID),
    UNIQUE KEY UK_BOARD_PROPERTY (BOARD_ID, PROPERTY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='보드 속성 설정';

-- TB_BOARD_PROPERTY 인덱스
CREATE INDEX IDX_BP_BOARD ON TB_BOARD_PROPERTY (BOARD_ID);
CREATE INDEX IDX_BP_PROPERTY ON TB_BOARD_PROPERTY (PROPERTY_ID);

-- ============================================
-- 7. TB_BOARD - 보드
-- ============================================
CREATE TABLE TB_BOARD (
    BOARD_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '보드 ID',
    BOARD_NAME VARCHAR(200) NOT NULL COMMENT '보드명',
    DESCRIPTION VARCHAR(500) NULL COMMENT '보드 설명',
    OWNER_USERNAME VARCHAR(50) NOT NULL COMMENT '소유자 USERNAME',
    DEFAULT_VIEW VARCHAR(20) NULL DEFAULT 'TABLE' COMMENT '기본 뷰 타입',
    COLOR VARCHAR(7) NULL COMMENT '색상 (#RRGGBB)',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (BOARD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='보드';

-- TB_BOARD 인덱스
CREATE INDEX IDX_BOARD_OWNER ON TB_BOARD (OWNER_USERNAME);
CREATE INDEX IDX_BOARD_USE ON TB_BOARD (USE_YN, SORT_ORDER);

-- ============================================
-- 7. TB_BOARD_SHARE - 보드 공유
-- ============================================
CREATE TABLE TB_BOARD_SHARE (
    BOARD_SHARE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '공유 ID',
    BOARD_ID BIGINT NOT NULL COMMENT '보드 ID',
    USERNAME VARCHAR(50) NOT NULL COMMENT '공유 사용자 USERNAME',
    PERMISSION VARCHAR(20) NOT NULL DEFAULT 'VIEW' COMMENT '권한 (VIEW/EDIT/FULL)',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (BOARD_SHARE_ID),
    UNIQUE KEY UK_BOARD_SHARE (BOARD_ID, USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='보드 공유';

-- TB_BOARD_SHARE 인덱스
CREATE INDEX IDX_BS_BOARD ON TB_BOARD_SHARE (BOARD_ID);
CREATE INDEX IDX_BS_USER ON TB_BOARD_SHARE (USERNAME);

-- ============================================
-- 8. TB_PROPERTY_DEF - 속성 정의 (v2.0: 소유자 기반)
-- ============================================
CREATE TABLE TB_PROPERTY_DEF (
    PROPERTY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '속성 ID',
    BOARD_ID BIGINT NULL COMMENT '보드 ID (레거시, USER 속성 보드 귀속 시 사용)',
    OWNER_TYPE VARCHAR(20) NOT NULL DEFAULT 'USER' COMMENT '소유 타입 (GLOBAL/MANAGER/USER)',
    OWNER_USERNAME VARCHAR(50) NULL COMMENT '소유자 USERNAME (MANAGER 타입)',
    OWNER_DEPT_CODE VARCHAR(20) NULL COMMENT '소유자 부서 코드 (MANAGER 타입)',
    PROPERTY_NAME VARCHAR(100) NOT NULL COMMENT '속성명',
    PROPERTY_TYPE VARCHAR(20) NOT NULL COMMENT '속성 타입',
    VISIBLE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '표시 여부',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (논리 삭제용)',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (PROPERTY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='속성 정의';

-- TB_PROPERTY_DEF 인덱스
CREATE INDEX IDX_PD_BOARD ON TB_PROPERTY_DEF (BOARD_ID, SORT_ORDER);
CREATE INDEX IDX_PD_VISIBLE ON TB_PROPERTY_DEF (BOARD_ID, VISIBLE_YN);
CREATE INDEX IDX_PD_USE ON TB_PROPERTY_DEF (BOARD_ID, USE_YN);
CREATE INDEX IDX_PD_OWNER_TYPE ON TB_PROPERTY_DEF (OWNER_TYPE);
CREATE INDEX IDX_PD_OWNER_USER ON TB_PROPERTY_DEF (OWNER_USERNAME);
CREATE INDEX IDX_PD_OWNER_DEPT ON TB_PROPERTY_DEF (OWNER_DEPT_CODE);

-- ============================================
-- 9. TB_PROPERTY_OPTION - 속성 옵션
-- ============================================
CREATE TABLE TB_PROPERTY_OPTION (
    OPTION_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '옵션 ID',
    PROPERTY_ID BIGINT NOT NULL COMMENT '속성 ID',
    OPTION_LABEL VARCHAR(100) NOT NULL COMMENT '옵션 라벨',
    COLOR VARCHAR(7) NULL COMMENT '색상 (#RRGGBB)',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (OPTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='속성 옵션';

-- TB_PROPERTY_OPTION 인덱스
CREATE INDEX IDX_PO_PROPERTY ON TB_PROPERTY_OPTION (PROPERTY_ID, SORT_ORDER);
CREATE INDEX IDX_PO_USE ON TB_PROPERTY_OPTION (PROPERTY_ID, USE_YN);

-- ============================================
-- 10. TB_ITEM - 업무 아이템
-- ============================================
CREATE TABLE TB_ITEM (
    ITEM_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '아이템 ID',
    BOARD_ID BIGINT NOT NULL COMMENT '보드 ID',
    CONTENT VARCHAR(500) NOT NULL COMMENT '업무 제목',
    DESCRIPTION TEXT NULL COMMENT '업무 상세 내용',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED' COMMENT '상태',
    PRIORITY VARCHAR(20) NOT NULL DEFAULT 'NORMAL' COMMENT '우선순위',
    CATEGORY_ID BIGINT NULL COMMENT '카테고리 ID',
    GROUP_ID BIGINT NULL COMMENT '그룹 ID',
    ASSIGNEE_USERNAME VARCHAR(50) NULL COMMENT '담당자 USERNAME',
    REQUEST_DATE DATE NULL COMMENT '요청일',
    DUE_DATE DATE NULL COMMENT '마감일',
    PREVIOUS_STATUS VARCHAR(20) NULL COMMENT '이전 상태',
    COMPLETED_BY VARCHAR(50) NULL COMMENT '완료 처리자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제 시간',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제 처리자 USERNAME',
    TRANSFERRED_FROM BIGINT NULL COMMENT '이관 원본 보드 ID',
    TRANSFERRED_AT DATETIME NULL COMMENT '이관 일시',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    PRIMARY KEY (ITEM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='업무 아이템';

-- TB_ITEM 인덱스
CREATE INDEX IDX_ITEM_BOARD ON TB_ITEM (BOARD_ID, STATUS);
CREATE INDEX IDX_ITEM_ASSIGNEE ON TB_ITEM (ASSIGNEE_USERNAME);
CREATE INDEX IDX_ITEM_GROUP ON TB_ITEM (GROUP_ID);
CREATE INDEX IDX_ITEM_CREATED ON TB_ITEM (BOARD_ID, CREATED_AT);
CREATE INDEX IDX_ITEM_DUE ON TB_ITEM (DUE_DATE);
CREATE INDEX IDX_ITEM_TRANSFERRED ON TB_ITEM (TRANSFERRED_FROM);
CREATE INDEX IDX_ITEM_CATEGORY ON TB_ITEM (CATEGORY_ID);

-- ============================================
-- 11. TB_ITEM_PROPERTY - 아이템 속성값
-- ============================================
CREATE TABLE TB_ITEM_PROPERTY (
    ITEM_PROPERTY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '속성값 ID',
    ITEM_ID BIGINT NOT NULL COMMENT '아이템 ID',
    PROPERTY_ID BIGINT NOT NULL COMMENT '속성 ID',
    VALUE_TEXT VARCHAR(1000) NULL COMMENT '텍스트 값',
    VALUE_NUMBER DECIMAL(18,4) NULL COMMENT '숫자 값',
    VALUE_DATE DATE NULL COMMENT '날짜 값',
    VALUE_OPTION_ID BIGINT NULL COMMENT '선택 옵션 ID',
    VALUE_USERNAME VARCHAR(50) NULL COMMENT '사용자 USERNAME (USER 타입)',
    VALUE_CHECKBOX CHAR(1) NULL COMMENT '체크박스 값 (Y/N)',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (ITEM_PROPERTY_ID),
    UNIQUE KEY UK_ITEM_PROPERTY (ITEM_ID, PROPERTY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='아이템 속성값';

-- TB_ITEM_PROPERTY 인덱스
CREATE INDEX IDX_IP_ITEM ON TB_ITEM_PROPERTY (ITEM_ID);
CREATE INDEX IDX_IP_ITEM_SORT ON TB_ITEM_PROPERTY (ITEM_ID, SORT_ORDER);
CREATE INDEX IDX_IP_PROPERTY ON TB_ITEM_PROPERTY (PROPERTY_ID);
CREATE INDEX IDX_IP_OPTION ON TB_ITEM_PROPERTY (VALUE_OPTION_ID);
CREATE INDEX IDX_IP_USER ON TB_ITEM_PROPERTY (VALUE_USERNAME);

-- ============================================
-- 12. TB_ITEM_PROPERTY_MULTI - 다중선택 속성값
-- ============================================
CREATE TABLE TB_ITEM_PROPERTY_MULTI (
    ITEM_PROPERTY_MULTI_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '다중선택 ID',
    ITEM_ID BIGINT NOT NULL COMMENT '아이템 ID',
    PROPERTY_ID BIGINT NOT NULL COMMENT '속성 ID',
    OPTION_ID BIGINT NOT NULL COMMENT '옵션 ID',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (ITEM_PROPERTY_MULTI_ID),
    UNIQUE KEY UK_ITEM_PROP_MULTI (ITEM_ID, PROPERTY_ID, OPTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='다중선택 속성값';

-- TB_ITEM_PROPERTY_MULTI 인덱스
CREATE INDEX IDX_IPM_ITEM ON TB_ITEM_PROPERTY_MULTI (ITEM_ID, PROPERTY_ID);
CREATE INDEX IDX_IPM_OPTION ON TB_ITEM_PROPERTY_MULTI (OPTION_ID);

-- ============================================
-- 13. TB_ITEM_SHARE - 업무 공유
-- ============================================
CREATE TABLE TB_ITEM_SHARE (
    ITEM_SHARE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '업무 공유 ID',
    ITEM_ID BIGINT NOT NULL COMMENT '업무 ID',
    USERNAME VARCHAR(50) NOT NULL COMMENT '공유받는 사용자 USERNAME',
    PERMISSION VARCHAR(20) NOT NULL DEFAULT 'VIEW' COMMENT '권한',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (ITEM_SHARE_ID),
    UNIQUE KEY UK_ITEM_SHARE (ITEM_ID, USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='업무 공유';

-- TB_ITEM_SHARE 인덱스
CREATE INDEX IDX_IS_ITEM ON TB_ITEM_SHARE (ITEM_ID);
CREATE INDEX IDX_IS_USER ON TB_ITEM_SHARE (USERNAME);

-- ============================================
-- 14. TB_COMMENT - 댓글
-- ============================================
CREATE TABLE TB_COMMENT (
    COMMENT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '댓글 ID',
    ITEM_ID BIGINT NOT NULL COMMENT '아이템 ID',
    CONTENT VARCHAR(2000) NOT NULL COMMENT '댓글 내용',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (COMMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='댓글';

-- TB_COMMENT 인덱스
CREATE INDEX IDX_CMT_ITEM ON TB_COMMENT (ITEM_ID, CREATED_AT);
CREATE INDEX IDX_CMT_USER ON TB_COMMENT (CREATED_BY);

-- ============================================
-- 15. TB_TASK_TEMPLATE - 작업 템플릿
-- ============================================
CREATE TABLE TB_TASK_TEMPLATE (
    TEMPLATE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '템플릿 ID',
    CONTENT VARCHAR(500) NOT NULL COMMENT '작업 내용',
    DEFAULT_ASSIGNEE_USERNAME VARCHAR(50) NULL COMMENT '기본 담당자 USERNAME',
    DEFAULT_ITEM_STATUS VARCHAR(20) NULL COMMENT '기본 업무 상태',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_COUNT INT NOT NULL DEFAULT 0 COMMENT '사용 횟수',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (TEMPLATE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='작업 템플릿';

-- TB_TASK_TEMPLATE 인덱스
CREATE INDEX IDX_TPL_USE ON TB_TASK_TEMPLATE (USE_YN);
CREATE INDEX IDX_TPL_CONTENT ON TB_TASK_TEMPLATE (CONTENT(100));
CREATE INDEX IDX_TPL_ASSIGNEE ON TB_TASK_TEMPLATE (DEFAULT_ASSIGNEE_USERNAME);

-- ============================================
-- 16. TB_AUDIT_LOG - 통합 감사 로그
-- ============================================
CREATE TABLE TB_AUDIT_LOG (
    LOG_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '로그 ID',
    TARGET_TYPE VARCHAR(20) NOT NULL COMMENT '대상 유형',
    TARGET_ID BIGINT NOT NULL COMMENT '대상 ID',
    ACTION VARCHAR(20) NOT NULL COMMENT '작업 유형',
    ACTOR_USERNAME VARCHAR(50) NOT NULL COMMENT '수행자 USERNAME',
    DESCRIPTION VARCHAR(500) NULL COMMENT '변경 내용 설명',
    BEFORE_DATA JSON NULL COMMENT '변경 전 데이터',
    AFTER_DATA JSON NULL COMMENT '변경 후 데이터',
    RELATED_USERNAME VARCHAR(50) NULL COMMENT '관련 사용자 USERNAME',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (LOG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='통합 감사 로그';

-- TB_AUDIT_LOG 인덱스
CREATE INDEX IDX_AL_TARGET ON TB_AUDIT_LOG (TARGET_TYPE, TARGET_ID);
CREATE INDEX IDX_AL_ACTOR ON TB_AUDIT_LOG (ACTOR_USERNAME);
CREATE INDEX IDX_AL_RELATED ON TB_AUDIT_LOG (RELATED_USERNAME);
CREATE INDEX IDX_AL_CREATED ON TB_AUDIT_LOG (CREATED_AT);
CREATE INDEX IDX_AL_ACTION ON TB_AUDIT_LOG (ACTION, CREATED_AT);

-- ============================================
-- 17. TB_FILE - 파일 메타데이터
-- ============================================
CREATE TABLE TB_FILE (
    FILE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '파일 ID',
    ORIGINAL_NAME VARCHAR(255) NOT NULL COMMENT '원본 파일명',
    STORED_NAME VARCHAR(255) NOT NULL COMMENT '저장된 파일명',
    EXTENSION VARCHAR(20) NULL COMMENT '파일 확장자',
    MIME_TYPE VARCHAR(100) NULL COMMENT 'MIME 타입',
    FILE_SIZE BIGINT NOT NULL DEFAULT 0 COMMENT '파일 크기',
    STORAGE_TYPE VARCHAR(20) NOT NULL DEFAULT 'LOCAL' COMMENT '스토리지 타입',
    STORAGE_PATH VARCHAR(500) NOT NULL COMMENT '스토리지 경로',
    STORAGE_BUCKET VARCHAR(100) NULL COMMENT 'S3 버킷명',
    RELATED_TYPE VARCHAR(50) NULL COMMENT '연관 타입',
    RELATED_ID BIGINT NULL COMMENT '연관 ID',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (FILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='파일 메타데이터';

-- TB_FILE 인덱스
CREATE INDEX IDX_FILE_RELATED ON TB_FILE (RELATED_TYPE, RELATED_ID);
CREATE INDEX IDX_FILE_STORAGE ON TB_FILE (STORAGE_TYPE, STORAGE_PATH(100));
CREATE INDEX IDX_FILE_CREATED ON TB_FILE (CREATED_BY, CREATED_AT);
CREATE INDEX IDX_FILE_USE ON TB_FILE (USE_YN);

-- ============================================
-- FOREIGN KEY 제약조건
-- ============================================

-- TB_DEPARTMENT FK (자기참조 - DEPARTMENT_CODE 기준)
ALTER TABLE TB_DEPARTMENT
    ADD CONSTRAINT FK_DEPT_PARENT
    FOREIGN KEY (PARENT_CODE) REFERENCES TB_DEPARTMENT (DEPARTMENT_CODE)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- TB_USER FK (DEPARTMENT_CODE, POSITION_CODE 참조)
ALTER TABLE TB_USER
    ADD CONSTRAINT FK_USER_DEPT
    FOREIGN KEY (DEPARTMENT_CODE) REFERENCES TB_DEPARTMENT (DEPARTMENT_CODE)
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE TB_USER
    ADD CONSTRAINT FK_USER_POSITION
    FOREIGN KEY (POSITION_CODE) REFERENCES TB_POSITION (POSITION_CODE)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- TB_GROUP FK
ALTER TABLE TB_GROUP
    ADD CONSTRAINT FK_GROUP_CREATED
    FOREIGN KEY (CREATED_BY) REFERENCES TB_USER (USERNAME)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- TB_USER_GROUP FK
ALTER TABLE TB_USER_GROUP
    ADD CONSTRAINT FK_UG_USER
    FOREIGN KEY (USERNAME) REFERENCES TB_USER (USERNAME)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_USER_GROUP
    ADD CONSTRAINT FK_UG_GROUP
    FOREIGN KEY (GROUP_ID) REFERENCES TB_GROUP (GROUP_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- TB_BOARD FK
ALTER TABLE TB_BOARD
    ADD CONSTRAINT FK_BOARD_OWNER
    FOREIGN KEY (OWNER_USERNAME) REFERENCES TB_USER (USERNAME)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- TB_BOARD_SHARE FK
ALTER TABLE TB_BOARD_SHARE
    ADD CONSTRAINT FK_BS_BOARD
    FOREIGN KEY (BOARD_ID) REFERENCES TB_BOARD (BOARD_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_BOARD_SHARE
    ADD CONSTRAINT FK_BS_USER
    FOREIGN KEY (USERNAME) REFERENCES TB_USER (USERNAME)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- TB_PROPERTY_DEF FK (v2.0: BOARD_ID nullable, 소유자 FK 추가)
ALTER TABLE TB_PROPERTY_DEF
    ADD CONSTRAINT FK_PD_BOARD
    FOREIGN KEY (BOARD_ID) REFERENCES TB_BOARD (BOARD_ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE TB_PROPERTY_DEF
    ADD CONSTRAINT FK_PD_OWNER_USER
    FOREIGN KEY (OWNER_USERNAME) REFERENCES TB_USER (USERNAME)
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE TB_PROPERTY_DEF
    ADD CONSTRAINT FK_PD_OWNER_DEPT
    FOREIGN KEY (OWNER_DEPT_CODE) REFERENCES TB_DEPARTMENT (DEPARTMENT_CODE)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- TB_PROPERTY_OPTION FK
ALTER TABLE TB_PROPERTY_OPTION
    ADD CONSTRAINT FK_PO_PROPERTY
    FOREIGN KEY (PROPERTY_ID) REFERENCES TB_PROPERTY_DEF (PROPERTY_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- TB_ITEM FK
ALTER TABLE TB_ITEM
    ADD CONSTRAINT FK_ITEM_BOARD
    FOREIGN KEY (BOARD_ID) REFERENCES TB_BOARD (BOARD_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_ITEM
    ADD CONSTRAINT FK_ITEM_CATEGORY
    FOREIGN KEY (CATEGORY_ID) REFERENCES TB_CATEGORY (CATEGORY_ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE TB_ITEM
    ADD CONSTRAINT FK_ITEM_GROUP
    FOREIGN KEY (GROUP_ID) REFERENCES TB_GROUP (GROUP_ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE TB_ITEM
    ADD CONSTRAINT FK_ITEM_ASSIGNEE
    FOREIGN KEY (ASSIGNEE_USERNAME) REFERENCES TB_USER (USERNAME)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- TB_ITEM_PROPERTY FK
ALTER TABLE TB_ITEM_PROPERTY
    ADD CONSTRAINT FK_IP_ITEM
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM (ITEM_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_ITEM_PROPERTY
    ADD CONSTRAINT FK_IP_PROPERTY
    FOREIGN KEY (PROPERTY_ID) REFERENCES TB_PROPERTY_DEF (PROPERTY_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_ITEM_PROPERTY
    ADD CONSTRAINT FK_IP_OPTION
    FOREIGN KEY (VALUE_OPTION_ID) REFERENCES TB_PROPERTY_OPTION (OPTION_ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE TB_ITEM_PROPERTY
    ADD CONSTRAINT FK_IP_USER
    FOREIGN KEY (VALUE_USERNAME) REFERENCES TB_USER (USERNAME)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- TB_ITEM_PROPERTY_MULTI FK
ALTER TABLE TB_ITEM_PROPERTY_MULTI
    ADD CONSTRAINT FK_IPM_ITEM
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM (ITEM_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_ITEM_PROPERTY_MULTI
    ADD CONSTRAINT FK_IPM_PROPERTY
    FOREIGN KEY (PROPERTY_ID) REFERENCES TB_PROPERTY_DEF (PROPERTY_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_ITEM_PROPERTY_MULTI
    ADD CONSTRAINT FK_IPM_OPTION
    FOREIGN KEY (OPTION_ID) REFERENCES TB_PROPERTY_OPTION (OPTION_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- TB_ITEM_SHARE FK
ALTER TABLE TB_ITEM_SHARE
    ADD CONSTRAINT FK_IS_ITEM
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM (ITEM_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_ITEM_SHARE
    ADD CONSTRAINT FK_IS_USER
    FOREIGN KEY (USERNAME) REFERENCES TB_USER (USERNAME)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- TB_COMMENT FK
ALTER TABLE TB_COMMENT
    ADD CONSTRAINT FK_CMT_ITEM
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM (ITEM_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_COMMENT
    ADD CONSTRAINT FK_CMT_USER
    FOREIGN KEY (CREATED_BY) REFERENCES TB_USER (USERNAME)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- TB_TASK_TEMPLATE FK
ALTER TABLE TB_TASK_TEMPLATE
    ADD CONSTRAINT FK_TPL_ASSIGNEE
    FOREIGN KEY (DEFAULT_ASSIGNEE_USERNAME) REFERENCES TB_USER (USERNAME)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- TB_FILE FK
ALTER TABLE TB_FILE
    ADD CONSTRAINT FK_FILE_CREATED
    FOREIGN KEY (CREATED_BY) REFERENCES TB_USER (USERNAME)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- TB_CATEGORY FK (v2.0)
ALTER TABLE TB_CATEGORY
    ADD CONSTRAINT FK_CATEGORY_OWNER
    FOREIGN KEY (OWNER_USERNAME) REFERENCES TB_USER (USERNAME)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- TB_CATEGORY_SHARE FK
ALTER TABLE TB_CATEGORY_SHARE
    ADD CONSTRAINT FK_CS_CATEGORY
    FOREIGN KEY (CATEGORY_ID) REFERENCES TB_CATEGORY (CATEGORY_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- TB_CATEGORY_PROPERTY FK
ALTER TABLE TB_CATEGORY_PROPERTY
    ADD CONSTRAINT FK_CP_CATEGORY
    FOREIGN KEY (CATEGORY_ID) REFERENCES TB_CATEGORY (CATEGORY_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_CATEGORY_PROPERTY
    ADD CONSTRAINT FK_CP_PROPERTY
    FOREIGN KEY (PROPERTY_ID) REFERENCES TB_PROPERTY_DEF (PROPERTY_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- TB_BOARD_CATEGORY FK
ALTER TABLE TB_BOARD_CATEGORY
    ADD CONSTRAINT FK_BC_BOARD
    FOREIGN KEY (BOARD_ID) REFERENCES TB_BOARD (BOARD_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_BOARD_CATEGORY
    ADD CONSTRAINT FK_BC_CATEGORY
    FOREIGN KEY (CATEGORY_ID) REFERENCES TB_CATEGORY (CATEGORY_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- TB_BOARD_PROPERTY FK (v2.0 신규)
ALTER TABLE TB_BOARD_PROPERTY
    ADD CONSTRAINT FK_BP_BOARD
    FOREIGN KEY (BOARD_ID) REFERENCES TB_BOARD (BOARD_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_BOARD_PROPERTY
    ADD CONSTRAINT FK_BP_PROPERTY
    FOREIGN KEY (PROPERTY_ID) REFERENCES TB_PROPERTY_DEF (PROPERTY_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- ============================================
-- 18. TB_ITEM_SCORE - 업무 성과 점수 (v2.0 설계서 기준)
-- ============================================
CREATE TABLE TB_ITEM_SCORE (
    SCORE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '점수 ID',
    ITEM_ID BIGINT NOT NULL COMMENT '업무 ID',

    -- 시간 기반 점수
    TIME_GRADE VARCHAR(20) NOT NULL COMMENT 'PERFECT, EXCELLENT, GREAT, GOOD, FAIR, POOR',
    TIME_SCORE DECIMAL(5,2) NOT NULL COMMENT '시간 기반 점수 (0~100)',
    COMPLETION_RATIO DECIMAL(5,4) NULL COMMENT '완료비율',

    -- 가중치: 난이도
    DIFFICULTY_CODE VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' COMMENT 'LOW, MEDIUM, HIGH, EXTREME',
    DIFFICULTY_WEIGHT DECIMAL(3,2) NOT NULL DEFAULT 1.0 COMMENT '난이도 가중치 (0.9~1.4)',

    -- 가중치: 범위변경
    SCOPE_CODE VARCHAR(20) NOT NULL DEFAULT 'NONE' COMMENT 'NONE, MINOR, MAJOR, CHAOS',
    SCOPE_WEIGHT DECIMAL(3,2) NOT NULL DEFAULT 1.0 COMMENT '범위변경 가중치 (1.0~1.3)',

    -- 가중치: 리스크대응
    RISK_CODE VARCHAR(20) NOT NULL DEFAULT 'NONE' COMMENT 'NONE, MITIGATED, CRITICAL',
    RISK_WEIGHT DECIMAL(3,2) NOT NULL DEFAULT 1.0 COMMENT '리스크 가중치 (1.0~1.25)',

    -- 최종 점수
    FINAL_SCORE DECIMAL(6,2) NOT NULL COMMENT '최종 점수',

    -- 계산 기준 날짜 (스냅샷)
    REQUEST_DATE DATE NULL COMMENT '요청일',
    START_DATE DATE NULL COMMENT '시작일',
    COMPLETION_DATE DATE NULL COMMENT '완료일',
    DUE_DATE DATE NULL COMMENT '마감일',
    ACTUAL_COMPLETION_AT DATETIME NULL COMMENT '실제 완료 처리일시',

    -- 승인 정보
    REQUIRES_APPROVAL CHAR(1) NOT NULL DEFAULT 'N' COMMENT '승인 필요 여부',
    APPROVED_YN CHAR(1) NULL COMMENT '승인 여부 (Y/N/NULL)',
    APPROVED_BY VARCHAR(50) NULL COMMENT '승인자 USERNAME',
    APPROVED_AT DATETIME NULL COMMENT '승인일시',

    -- 계산 정보
    CALCULATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '계산일시',
    CALCULATED_BY VARCHAR(50) NOT NULL COMMENT '계산자 USERNAME',

    -- 논리삭제
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',

    PRIMARY KEY (SCORE_ID),
    UNIQUE KEY UK_ITEM_SCORE (ITEM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='업무 성과 점수';

-- TB_ITEM_SCORE 인덱스
CREATE INDEX IDX_SCORE_GRADE ON TB_ITEM_SCORE (TIME_GRADE);
CREATE INDEX IDX_SCORE_CALC ON TB_ITEM_SCORE (CALCULATED_AT);
CREATE INDEX IDX_SCORE_APPROVAL ON TB_ITEM_SCORE (REQUIRES_APPROVAL, APPROVED_YN);

-- TB_ITEM_SCORE FK
ALTER TABLE TB_ITEM_SCORE
    ADD CONSTRAINT FK_SCORE_ITEM
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM (ITEM_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
