-- ============================================
-- TaskFlow Database Schema
-- MySQL 8.0+
-- ============================================

-- 데이터베이스 설정
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

-- ============================================
-- 1. TB_DEPARTMENT - 부서
-- ============================================
CREATE TABLE TB_DEPARTMENT (
    DEPARTMENT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '부서 ID',
    DEPARTMENT_CODE VARCHAR(20) NOT NULL COMMENT '부서 코드',
    DEPARTMENT_NAME VARCHAR(100) NOT NULL COMMENT '부서명',
    PARENT_ID BIGINT NULL COMMENT '상위 부서 ID',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY BIGINT NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY BIGINT NULL COMMENT '수정자',
    PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT UK_DEPARTMENT_CODE UNIQUE (DEPARTMENT_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='부서';

-- TB_DEPARTMENT 인덱스
CREATE INDEX IDX_DEPARTMENT_PARENT ON TB_DEPARTMENT (PARENT_ID);
CREATE INDEX IDX_DEPARTMENT_USE ON TB_DEPARTMENT (USE_YN, SORT_ORDER);

-- ============================================
-- 2. TB_USER - 사용자
-- ============================================
CREATE TABLE TB_USER (
    USER_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '사용자 ID',
    USERNAME VARCHAR(50) NOT NULL COMMENT '로그인 ID',
    PASSWORD VARCHAR(255) NOT NULL COMMENT '비밀번호 (BCrypt)',
    NAME VARCHAR(100) NOT NULL COMMENT '사용자 이름',
    EMAIL VARCHAR(100) NULL COMMENT '이메일 주소',
    DEPARTMENT_ID BIGINT NULL COMMENT '부서 ID',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    LAST_LOGIN_AT DATETIME NULL COMMENT '마지막 로그인 일시',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY BIGINT NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY BIGINT NULL COMMENT '수정자',
    PRIMARY KEY (USER_ID),
    CONSTRAINT UK_USER_USERNAME UNIQUE (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자';

-- TB_USER 인덱스
CREATE INDEX IDX_USER_DEPARTMENT ON TB_USER (DEPARTMENT_ID);
CREATE INDEX IDX_USER_USE ON TB_USER (USE_YN);
CREATE INDEX IDX_USER_NAME ON TB_USER (NAME);

-- ============================================
-- 3. TB_GROUP - 그룹
-- ============================================
CREATE TABLE TB_GROUP (
    GROUP_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '그룹 ID',
    GROUP_CODE VARCHAR(20) NOT NULL COMMENT '그룹 코드',
    GROUP_NAME VARCHAR(100) NOT NULL COMMENT '그룹명',
    DESCRIPTION VARCHAR(500) NULL COMMENT '그룹 설명',
    GROUP_COLOR VARCHAR(7) NULL COMMENT '색상 (#RRGGBB)',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY BIGINT NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY BIGINT NULL COMMENT '수정자',
    PRIMARY KEY (GROUP_ID),
    CONSTRAINT UK_GROUP_CODE UNIQUE (GROUP_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='그룹';

-- TB_GROUP 인덱스
CREATE INDEX IDX_GROUP_USE ON TB_GROUP (USE_YN, SORT_ORDER);

-- ============================================
-- 4. TB_USER_GROUP - 사용자-그룹 매핑
-- ============================================
CREATE TABLE TB_USER_GROUP (
    USER_GROUP_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '매핑 ID',
    USER_ID BIGINT NOT NULL COMMENT '사용자 ID',
    GROUP_ID BIGINT NOT NULL COMMENT '그룹 ID',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY BIGINT NOT NULL COMMENT '생성자',
    PRIMARY KEY (USER_GROUP_ID),
    CONSTRAINT UK_USER_GROUP UNIQUE (USER_ID, GROUP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자-그룹 매핑';

-- TB_USER_GROUP 인덱스
CREATE INDEX IDX_USER_GROUP_USER ON TB_USER_GROUP (USER_ID);
CREATE INDEX IDX_USER_GROUP_GROUP ON TB_USER_GROUP (GROUP_ID);

-- ============================================
-- 5. TB_BOARD - 보드
-- ============================================
CREATE TABLE TB_BOARD (
    BOARD_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '보드 ID',
    BOARD_NAME VARCHAR(200) NOT NULL COMMENT '보드명',
    DESCRIPTION VARCHAR(500) NULL COMMENT '보드 설명',
    OWNER_ID BIGINT NOT NULL COMMENT '소유자 ID',
    DEFAULT_VIEW VARCHAR(20) NULL DEFAULT 'TABLE' COMMENT '기본 뷰 타입 (TABLE/KANBAN/LIST)',
    COLOR VARCHAR(7) NULL COMMENT '색상 (#RRGGBB)',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY BIGINT NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY BIGINT NULL COMMENT '수정자',
    PRIMARY KEY (BOARD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='보드';

-- TB_BOARD 인덱스
CREATE INDEX IDX_BOARD_OWNER ON TB_BOARD (OWNER_ID);
CREATE INDEX IDX_BOARD_USE ON TB_BOARD (USE_YN, SORT_ORDER);

-- ============================================
-- 6. TB_BOARD_SHARE - 보드 공유
-- ============================================
CREATE TABLE TB_BOARD_SHARE (
    BOARD_SHARE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '공유 ID',
    BOARD_ID BIGINT NOT NULL COMMENT '보드 ID',
    USER_ID BIGINT NOT NULL COMMENT '공유 사용자 ID',
    PERMISSION VARCHAR(20) NOT NULL DEFAULT 'MEMBER' COMMENT '권한 (MEMBER/VIEWER)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY BIGINT NOT NULL COMMENT '생성자',
    PRIMARY KEY (BOARD_SHARE_ID),
    CONSTRAINT UK_BOARD_SHARE UNIQUE (BOARD_ID, USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='보드 공유';

-- TB_BOARD_SHARE 인덱스
CREATE INDEX IDX_BOARD_SHARE_BOARD ON TB_BOARD_SHARE (BOARD_ID);
CREATE INDEX IDX_BOARD_SHARE_USER ON TB_BOARD_SHARE (USER_ID);

-- ============================================
-- 7. TB_PROPERTY_DEF - 속성 정의
-- ============================================
CREATE TABLE TB_PROPERTY_DEF (
    PROPERTY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '속성 ID',
    BOARD_ID BIGINT NOT NULL COMMENT '보드 ID',
    PROPERTY_NAME VARCHAR(100) NOT NULL COMMENT '속성명',
    PROPERTY_TYPE VARCHAR(20) NOT NULL COMMENT '속성 타입 (TEXT/NUMBER/DATE/SELECT/MULTI_SELECT/CHECKBOX/USER)',
    REQUIRED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '필수 여부 (Y/N)',
    VISIBLE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '표시 여부 (Y/N)',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY BIGINT NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY BIGINT NULL COMMENT '수정자',
    PRIMARY KEY (PROPERTY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='속성 정의';

-- TB_PROPERTY_DEF 인덱스
CREATE INDEX IDX_PROPERTY_DEF_BOARD ON TB_PROPERTY_DEF (BOARD_ID, SORT_ORDER);
CREATE INDEX IDX_PROPERTY_DEF_VISIBLE ON TB_PROPERTY_DEF (BOARD_ID, VISIBLE_YN);

-- ============================================
-- 8. TB_PROPERTY_OPTION - 속성 옵션
-- ============================================
CREATE TABLE TB_PROPERTY_OPTION (
    OPTION_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '옵션 ID',
    PROPERTY_ID BIGINT NOT NULL COMMENT '속성 ID',
    OPTION_LABEL VARCHAR(100) NOT NULL COMMENT '옵션 라벨',
    COLOR VARCHAR(7) NULL COMMENT '색상 (#RRGGBB)',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY BIGINT NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY BIGINT NULL COMMENT '수정자',
    PRIMARY KEY (OPTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='속성 옵션';

-- TB_PROPERTY_OPTION 인덱스
CREATE INDEX IDX_PROPERTY_OPTION_PROPERTY ON TB_PROPERTY_OPTION (PROPERTY_ID, SORT_ORDER);
CREATE INDEX IDX_PROPERTY_OPTION_USE ON TB_PROPERTY_OPTION (PROPERTY_ID, USE_YN);

-- ============================================
-- 9. TB_ITEM - 업무 아이템
-- ============================================
CREATE TABLE TB_ITEM (
    ITEM_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '아이템 ID',
    BOARD_ID BIGINT NOT NULL COMMENT '보드 ID',
    CONTENT VARCHAR(500) NOT NULL COMMENT '업무 제목',
    DESCRIPTION TEXT NULL COMMENT '업무 상세 내용 (마크다운)',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED' COMMENT '상태 (NOT_STARTED/IN_PROGRESS/COMPLETED/DELETED)',
    PRIORITY VARCHAR(20) NOT NULL DEFAULT 'NORMAL' COMMENT '우선순위 (URGENT/HIGH/NORMAL/LOW)',
    CATEGORY_ID BIGINT NULL COMMENT '카테고리 옵션 ID',
    GROUP_ID BIGINT NULL COMMENT '그룹 ID',
    ASSIGNEE_ID BIGINT NULL COMMENT '담당자 ID',
    START_TIME DATETIME NULL COMMENT '시작 시간',
    END_TIME DATETIME NULL COMMENT '완료 시간',
    PREVIOUS_STATUS VARCHAR(20) NULL COMMENT '이전 상태 (삭제/복원 전 상태)',
    COMPLETED_BY BIGINT NULL COMMENT '완료 처리자 ID',
    DELETED_AT DATETIME NULL COMMENT '삭제 시간',
    DELETED_BY BIGINT NULL COMMENT '삭제 처리자 ID',
    TRANSFERRED_FROM BIGINT NULL COMMENT '이관 원본 보드 ID',
    TRANSFERRED_AT DATETIME NULL COMMENT '이관 일시',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY BIGINT NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY BIGINT NULL COMMENT '수정자',
    PRIMARY KEY (ITEM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='업무 아이템';

-- TB_ITEM 인덱스
CREATE INDEX IDX_ITEM_BOARD_STATUS ON TB_ITEM (BOARD_ID, STATUS);
CREATE INDEX IDX_ITEM_ASSIGNEE ON TB_ITEM (ASSIGNEE_ID);
CREATE INDEX IDX_ITEM_GROUP ON TB_ITEM (GROUP_ID);
CREATE INDEX IDX_ITEM_CREATED ON TB_ITEM (BOARD_ID, CREATED_AT);
CREATE INDEX IDX_ITEM_END_TIME ON TB_ITEM (END_TIME);
CREATE INDEX IDX_ITEM_TRANSFERRED ON TB_ITEM (TRANSFERRED_FROM);

-- ============================================
-- 10. TB_ITEM_PROPERTY - 아이템 속성값
-- ============================================
CREATE TABLE TB_ITEM_PROPERTY (
    ITEM_PROPERTY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '속성값 ID',
    ITEM_ID BIGINT NOT NULL COMMENT '아이템 ID',
    PROPERTY_ID BIGINT NOT NULL COMMENT '속성 ID',
    VALUE_TEXT VARCHAR(1000) NULL COMMENT '텍스트 값 (TEXT 타입)',
    VALUE_NUMBER DECIMAL(18,4) NULL COMMENT '숫자 값 (NUMBER 타입)',
    VALUE_DATE DATE NULL COMMENT '날짜 값 (DATE 타입)',
    VALUE_OPTION_ID BIGINT NULL COMMENT '선택 옵션 ID (SELECT 타입)',
    VALUE_USER_ID BIGINT NULL COMMENT '사용자 ID (USER 타입)',
    VALUE_CHECKBOX CHAR(1) NULL COMMENT '체크박스 값 (CHECKBOX 타입, Y/N)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY BIGINT NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY BIGINT NULL COMMENT '수정자',
    PRIMARY KEY (ITEM_PROPERTY_ID),
    CONSTRAINT UK_ITEM_PROPERTY UNIQUE (ITEM_ID, PROPERTY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='아이템 속성값';

-- TB_ITEM_PROPERTY 인덱스
CREATE INDEX IDX_ITEM_PROPERTY_ITEM ON TB_ITEM_PROPERTY (ITEM_ID);
CREATE INDEX IDX_ITEM_PROPERTY_PROPERTY ON TB_ITEM_PROPERTY (PROPERTY_ID);
CREATE INDEX IDX_ITEM_PROPERTY_OPTION ON TB_ITEM_PROPERTY (VALUE_OPTION_ID);

-- ============================================
-- 11. TB_ITEM_PROPERTY_MULTI - 다중선택 속성값
-- ============================================
CREATE TABLE TB_ITEM_PROPERTY_MULTI (
    ITEM_PROPERTY_MULTI_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '다중선택 ID',
    ITEM_ID BIGINT NOT NULL COMMENT '아이템 ID',
    PROPERTY_ID BIGINT NOT NULL COMMENT '속성 ID',
    OPTION_ID BIGINT NOT NULL COMMENT '옵션 ID',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY BIGINT NOT NULL COMMENT '생성자',
    PRIMARY KEY (ITEM_PROPERTY_MULTI_ID),
    CONSTRAINT UK_ITEM_PROPERTY_MULTI UNIQUE (ITEM_ID, PROPERTY_ID, OPTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='다중선택 속성값';

-- TB_ITEM_PROPERTY_MULTI 인덱스
CREATE INDEX IDX_ITEM_PROP_MULTI_ITEM ON TB_ITEM_PROPERTY_MULTI (ITEM_ID, PROPERTY_ID);
CREATE INDEX IDX_ITEM_PROP_MULTI_OPTION ON TB_ITEM_PROPERTY_MULTI (OPTION_ID);

-- ============================================
-- 12. TB_COMMENT - 댓글
-- ============================================
CREATE TABLE TB_COMMENT (
    COMMENT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '댓글 ID',
    ITEM_ID BIGINT NOT NULL COMMENT '아이템 ID',
    CONTENT VARCHAR(2000) NOT NULL COMMENT '댓글 내용',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY BIGINT NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY BIGINT NULL COMMENT '수정자',
    PRIMARY KEY (COMMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='댓글';

-- TB_COMMENT 인덱스
CREATE INDEX IDX_COMMENT_ITEM ON TB_COMMENT (ITEM_ID, CREATED_AT);

-- ============================================
-- 13. TB_TASK_TEMPLATE - 작업 템플릿
-- ============================================
CREATE TABLE TB_TASK_TEMPLATE (
    TEMPLATE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '템플릿 ID',
    CONTENT VARCHAR(500) NOT NULL COMMENT '작업 내용',
    DEFAULT_ASSIGNEE_ID BIGINT NULL COMMENT '기본 담당자 ID',
    DEFAULT_ITEM_STATUS VARCHAR(20) NULL COMMENT '기본 업무 상태',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_COUNT INT NOT NULL DEFAULT 0 COMMENT '사용 횟수',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY BIGINT NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY BIGINT NULL COMMENT '수정자',
    PRIMARY KEY (TEMPLATE_ID),
    CONSTRAINT FK_TEMPLATE_ASSIGNEE FOREIGN KEY (DEFAULT_ASSIGNEE_ID) REFERENCES TB_USER(USER_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='작업 템플릿';

-- TB_TASK_TEMPLATE 인덱스
CREATE INDEX IDX_TASK_TEMPLATE_USE ON TB_TASK_TEMPLATE (USE_YN);
CREATE INDEX IDX_TASK_TEMPLATE_CONTENT ON TB_TASK_TEMPLATE (CONTENT(100));

-- ============================================
-- FOREIGN KEY 제약조건
-- ============================================

-- TB_DEPARTMENT FK (자기참조)
ALTER TABLE TB_DEPARTMENT
    ADD CONSTRAINT FK_DEPARTMENT_PARENT
    FOREIGN KEY (PARENT_ID) REFERENCES TB_DEPARTMENT (DEPARTMENT_ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- TB_USER FK
ALTER TABLE TB_USER
    ADD CONSTRAINT FK_USER_DEPARTMENT
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES TB_DEPARTMENT (DEPARTMENT_ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- TB_USER_GROUP FK
ALTER TABLE TB_USER_GROUP
    ADD CONSTRAINT FK_USER_GROUP_USER
    FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_USER_GROUP
    ADD CONSTRAINT FK_USER_GROUP_GROUP
    FOREIGN KEY (GROUP_ID) REFERENCES TB_GROUP (GROUP_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- TB_BOARD FK
ALTER TABLE TB_BOARD
    ADD CONSTRAINT FK_BOARD_OWNER
    FOREIGN KEY (OWNER_ID) REFERENCES TB_USER (USER_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- TB_BOARD_SHARE FK
ALTER TABLE TB_BOARD_SHARE
    ADD CONSTRAINT FK_BOARD_SHARE_BOARD
    FOREIGN KEY (BOARD_ID) REFERENCES TB_BOARD (BOARD_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_BOARD_SHARE
    ADD CONSTRAINT FK_BOARD_SHARE_USER
    FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- TB_PROPERTY_DEF FK
ALTER TABLE TB_PROPERTY_DEF
    ADD CONSTRAINT FK_PROPERTY_DEF_BOARD
    FOREIGN KEY (BOARD_ID) REFERENCES TB_BOARD (BOARD_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- TB_PROPERTY_OPTION FK
ALTER TABLE TB_PROPERTY_OPTION
    ADD CONSTRAINT FK_PROPERTY_OPTION_PROPERTY
    FOREIGN KEY (PROPERTY_ID) REFERENCES TB_PROPERTY_DEF (PROPERTY_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- TB_ITEM FK
ALTER TABLE TB_ITEM
    ADD CONSTRAINT FK_ITEM_BOARD
    FOREIGN KEY (BOARD_ID) REFERENCES TB_BOARD (BOARD_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_ITEM
    ADD CONSTRAINT FK_ITEM_CATEGORY
    FOREIGN KEY (CATEGORY_ID) REFERENCES TB_PROPERTY_OPTION (OPTION_ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE TB_ITEM
    ADD CONSTRAINT FK_ITEM_GROUP
    FOREIGN KEY (GROUP_ID) REFERENCES TB_GROUP (GROUP_ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE TB_ITEM
    ADD CONSTRAINT FK_ITEM_ASSIGNEE
    FOREIGN KEY (ASSIGNEE_ID) REFERENCES TB_USER (USER_ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- TB_ITEM_PROPERTY FK
ALTER TABLE TB_ITEM_PROPERTY
    ADD CONSTRAINT FK_ITEM_PROPERTY_ITEM
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM (ITEM_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_ITEM_PROPERTY
    ADD CONSTRAINT FK_ITEM_PROPERTY_PROPERTY
    FOREIGN KEY (PROPERTY_ID) REFERENCES TB_PROPERTY_DEF (PROPERTY_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_ITEM_PROPERTY
    ADD CONSTRAINT FK_ITEM_PROPERTY_OPTION
    FOREIGN KEY (VALUE_OPTION_ID) REFERENCES TB_PROPERTY_OPTION (OPTION_ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE TB_ITEM_PROPERTY
    ADD CONSTRAINT FK_ITEM_PROPERTY_USER
    FOREIGN KEY (VALUE_USER_ID) REFERENCES TB_USER (USER_ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- TB_ITEM_PROPERTY_MULTI FK
ALTER TABLE TB_ITEM_PROPERTY_MULTI
    ADD CONSTRAINT FK_ITEM_PROP_MULTI_ITEM
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM (ITEM_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_ITEM_PROPERTY_MULTI
    ADD CONSTRAINT FK_ITEM_PROP_MULTI_PROPERTY
    FOREIGN KEY (PROPERTY_ID) REFERENCES TB_PROPERTY_DEF (PROPERTY_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_ITEM_PROPERTY_MULTI
    ADD CONSTRAINT FK_ITEM_PROP_MULTI_OPTION
    FOREIGN KEY (OPTION_ID) REFERENCES TB_PROPERTY_OPTION (OPTION_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- TB_COMMENT FK
ALTER TABLE TB_COMMENT
    ADD CONSTRAINT FK_COMMENT_ITEM
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM (ITEM_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- ============================================
-- 14. TB_ITEM_SHARE - 업무 공유
-- ============================================
CREATE TABLE TB_ITEM_SHARE (
    ITEM_SHARE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '업무 공유 ID',
    ITEM_ID BIGINT NOT NULL COMMENT '업무 ID',
    USER_ID BIGINT NOT NULL COMMENT '공유받는 사용자 ID',
    PERMISSION VARCHAR(20) NOT NULL COMMENT '권한 (VIEW/EDIT/FULL)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY BIGINT NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY BIGINT NULL COMMENT '수정자',
    PRIMARY KEY (ITEM_SHARE_ID),
    CONSTRAINT UK_ITEM_SHARE UNIQUE (ITEM_ID, USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='업무 공유';

-- TB_ITEM_SHARE 인덱스
CREATE INDEX IDX_ITEM_SHARE_ITEM ON TB_ITEM_SHARE (ITEM_ID);
CREATE INDEX IDX_ITEM_SHARE_USER ON TB_ITEM_SHARE (USER_ID);

-- TB_ITEM_SHARE FK
ALTER TABLE TB_ITEM_SHARE
    ADD CONSTRAINT FK_ITEM_SHARE_ITEM
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM (ITEM_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_ITEM_SHARE
    ADD CONSTRAINT FK_ITEM_SHARE_USER
    FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- ============================================
-- 15. TB_AUDIT_LOG - 통합 감사 로그
-- ============================================
CREATE TABLE TB_AUDIT_LOG (
    LOG_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '로그 ID',
    TARGET_TYPE VARCHAR(20) NOT NULL COMMENT '대상 유형 (BOARD/ITEM/BOARD_SHARE/ITEM_SHARE)',
    TARGET_ID BIGINT NOT NULL COMMENT '대상 ID',
    ACTION VARCHAR(20) NOT NULL COMMENT '작업 유형 (CREATE/UPDATE/DELETE/TRANSFER/SHARE/UNSHARE)',
    ACTOR_ID BIGINT NOT NULL COMMENT '수행자 ID',
    DESCRIPTION VARCHAR(500) NULL COMMENT '변경 내용 설명',
    BEFORE_DATA JSON NULL COMMENT '변경 전 데이터',
    AFTER_DATA JSON NULL COMMENT '변경 후 데이터',
    RELATED_USER_ID BIGINT NULL COMMENT '관련 사용자 ID (이관/공유 대상)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (LOG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='통합 감사 로그';

-- TB_AUDIT_LOG 인덱스
CREATE INDEX IDX_AUDIT_LOG_TARGET ON TB_AUDIT_LOG (TARGET_TYPE, TARGET_ID);
CREATE INDEX IDX_AUDIT_LOG_ACTOR ON TB_AUDIT_LOG (ACTOR_ID);
CREATE INDEX IDX_AUDIT_LOG_CREATED ON TB_AUDIT_LOG (CREATED_AT);
CREATE INDEX IDX_AUDIT_LOG_ACTION ON TB_AUDIT_LOG (ACTION, CREATED_AT);

-- TB_AUDIT_LOG FK
ALTER TABLE TB_AUDIT_LOG
    ADD CONSTRAINT FK_AUDIT_LOG_ACTOR
    FOREIGN KEY (ACTOR_ID) REFERENCES TB_USER (USER_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- ============================================
-- 16. TB_FILE - 파일 메타데이터
-- ============================================
CREATE TABLE TB_FILE (
    FILE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '파일 ID',

    -- 원본 파일 정보
    ORIGINAL_NAME VARCHAR(255) NOT NULL COMMENT '원본 파일명',
    STORED_NAME VARCHAR(255) NOT NULL COMMENT '저장된 파일명 (UUID)',
    EXTENSION VARCHAR(20) NULL COMMENT '파일 확장자',
    MIME_TYPE VARCHAR(100) NULL COMMENT 'MIME 타입',
    FILE_SIZE BIGINT NOT NULL DEFAULT 0 COMMENT '파일 크기 (bytes)',

    -- 스토리지 정보 (마이그레이션 지원)
    STORAGE_TYPE VARCHAR(20) NOT NULL DEFAULT 'LOCAL' COMMENT 'LOCAL, NAS, S3',
    STORAGE_PATH VARCHAR(500) NOT NULL COMMENT '스토리지 내 상대 경로',
    STORAGE_BUCKET VARCHAR(100) NULL COMMENT 'S3 버킷명 또는 NAS 공유명',

    -- 연관 정보
    RELATED_TYPE VARCHAR(50) NULL COMMENT 'ITEM, COMMENT, USER 등',
    RELATED_ID BIGINT NULL COMMENT '연관 엔티티 ID',

    -- 상태
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',

    -- 공통
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY BIGINT NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY BIGINT NULL COMMENT '수정자',

    PRIMARY KEY (FILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='파일 메타데이터';

-- TB_FILE 인덱스
CREATE INDEX IDX_FILE_RELATED ON TB_FILE (RELATED_TYPE, RELATED_ID);
CREATE INDEX IDX_FILE_STORAGE ON TB_FILE (STORAGE_TYPE, STORAGE_PATH(100));
CREATE INDEX IDX_FILE_CREATED ON TB_FILE (CREATED_BY, CREATED_AT);
CREATE INDEX IDX_FILE_USE ON TB_FILE (USE_YN);

-- TB_FILE FK
ALTER TABLE TB_FILE
    ADD CONSTRAINT FK_FILE_CREATED_BY
    FOREIGN KEY (CREATED_BY) REFERENCES TB_USER (USER_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- ============================================
-- 참고: TB_ITEM.TRANSFERRED_FROM, TRANSFERRED_AT 컬럼은
-- CREATE TABLE TB_ITEM에 이미 포함되어 있음
-- ============================================

-- ============================================
-- 참고: TB_BOARD_SHARE.PERMISSION
-- 현재 운영 DB 기본값: 'MEMBER' (MEMBER/VIEWER)
-- 추후 마이그레이션 필요 시 아래 스크립트 사용:
-- ALTER TABLE TB_BOARD_SHARE
--     MODIFY COLUMN PERMISSION VARCHAR(20) NOT NULL DEFAULT 'VIEW' COMMENT '권한 (VIEW/EDIT/FULL)';
-- UPDATE TB_BOARD_SHARE SET PERMISSION = 'VIEW' WHERE PERMISSION = 'VIEWER';
-- UPDATE TB_BOARD_SHARE SET PERMISSION = 'EDIT' WHERE PERMISSION = 'MEMBER';
-- ============================================
