-- ============================================
-- TaskFlow 2.0 Schema Migration
-- Version: 2.0
-- Date: 2025-01-04
-- ============================================

-- ============================================
-- 1. TB_PROPERTY_DEF 수정
-- ============================================

-- BOARD_ID NULL 허용 (글로벌/매니저 속성은 보드 미귀속)
ALTER TABLE TB_PROPERTY_DEF
  MODIFY COLUMN BOARD_ID BIGINT NULL COMMENT '보드 ID (NULL: 보드 미귀속 속성)';

-- 새 컬럼 추가
ALTER TABLE TB_PROPERTY_DEF
  ADD COLUMN OWNER_TYPE VARCHAR(20) NOT NULL DEFAULT 'USER'
      COMMENT '소유 유형 (GLOBAL, MANAGER, USER)' AFTER BOARD_ID,
  ADD COLUMN OWNER_USERNAME VARCHAR(50) NULL
      COMMENT '소유자 USERNAME (GLOBAL은 NULL)' AFTER OWNER_TYPE,
  ADD COLUMN OWNER_DEPT_CODE VARCHAR(20) NULL
      COMMENT '매니저 속성의 부서 코드 (적용 범위)' AFTER OWNER_USERNAME;

-- 인덱스 추가
CREATE INDEX IDX_PROP_OWNER_TYPE ON TB_PROPERTY_DEF (OWNER_TYPE);
CREATE INDEX IDX_PROP_OWNER_USER ON TB_PROPERTY_DEF (OWNER_USERNAME);
CREATE INDEX IDX_PROP_OWNER_DEPT ON TB_PROPERTY_DEF (OWNER_DEPT_CODE);

-- 기존 데이터 마이그레이션: 기존 보드 귀속 속성은 USER 타입으로 유지
UPDATE TB_PROPERTY_DEF SET OWNER_TYPE = 'USER' WHERE BOARD_ID IS NOT NULL;

-- ============================================
-- 2. TB_CATEGORY (카테고리)
-- ============================================

CREATE TABLE IF NOT EXISTS TB_CATEGORY (
    CATEGORY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '카테고리 ID',
    CATEGORY_CODE VARCHAR(50) NOT NULL COMMENT '카테고리 코드',
    CATEGORY_NAME VARCHAR(100) NOT NULL COMMENT '카테고리명',
    DESCRIPTION VARCHAR(500) NULL COMMENT '설명',
    CATEGORY_COLOR VARCHAR(7) NULL COMMENT '색상 코드 (#RRGGBB)',
    OWNER_USERNAME VARCHAR(50) NOT NULL COMMENT '소유자 USERNAME',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50) NOT NULL,
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50) NULL,
    PRIMARY KEY (CATEGORY_ID),
    UNIQUE KEY UK_CATEGORY_CODE (OWNER_USERNAME, CATEGORY_CODE),
    INDEX IDX_CATEGORY_OWNER (OWNER_USERNAME, USE_YN),
    CONSTRAINT FK_CATEGORY_OWNER FOREIGN KEY (OWNER_USERNAME)
        REFERENCES TB_USER(USERNAME) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT '카테고리 (속성 그룹)';

-- ============================================
-- 3. TB_CATEGORY_SHARE (카테고리 공유)
-- ============================================

CREATE TABLE IF NOT EXISTS TB_CATEGORY_SHARE (
    SHARE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '공유 ID',
    CATEGORY_ID BIGINT NOT NULL COMMENT '카테고리 ID',
    SHARE_TYPE VARCHAR(20) NOT NULL COMMENT '공유 대상 유형 (USER, DEPARTMENT)',
    SHARE_TARGET VARCHAR(50) NOT NULL COMMENT '공유 대상 (USERNAME 또는 DEPT_CODE)',
    PERMISSION VARCHAR(20) NOT NULL DEFAULT 'READ' COMMENT '권한 (READ, EDIT)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50) NOT NULL,
    PRIMARY KEY (SHARE_ID),
    UNIQUE KEY UK_CAT_SHARE (CATEGORY_ID, SHARE_TYPE, SHARE_TARGET),
    INDEX IDX_CAT_SHARE_TARGET (SHARE_TYPE, SHARE_TARGET),
    CONSTRAINT FK_CAT_SHARE_CATEGORY FOREIGN KEY (CATEGORY_ID)
        REFERENCES TB_CATEGORY(CATEGORY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT '카테고리 공유';

-- ============================================
-- 4. TB_CATEGORY_PROPERTY (카테고리-속성 매핑)
-- ============================================

CREATE TABLE IF NOT EXISTS TB_CATEGORY_PROPERTY (
    CATEGORY_PROPERTY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '매핑 ID',
    CATEGORY_ID BIGINT NOT NULL COMMENT '카테고리 ID',
    PROPERTY_ID BIGINT NOT NULL COMMENT '속성 ID',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '속성 표시 순서',
    DEFAULT_VALUE VARCHAR(500) NULL COMMENT '기본값',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50) NOT NULL,
    PRIMARY KEY (CATEGORY_PROPERTY_ID),
    UNIQUE KEY UK_CAT_PROP (CATEGORY_ID, PROPERTY_ID),
    INDEX IDX_CAT_PROP_CAT (CATEGORY_ID),
    INDEX IDX_CAT_PROP_PROP (PROPERTY_ID),
    CONSTRAINT FK_CAT_PROP_CATEGORY FOREIGN KEY (CATEGORY_ID)
        REFERENCES TB_CATEGORY(CATEGORY_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CAT_PROP_PROPERTY FOREIGN KEY (PROPERTY_ID)
        REFERENCES TB_PROPERTY_DEF(PROPERTY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT '카테고리-속성 매핑';

-- ============================================
-- 5. TB_BOARD_CATEGORY (보드-카테고리 매핑)
-- ============================================

CREATE TABLE IF NOT EXISTS TB_BOARD_CATEGORY (
    BOARD_CATEGORY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '매핑 ID',
    BOARD_ID BIGINT NOT NULL COMMENT '보드 ID',
    CATEGORY_ID BIGINT NOT NULL COMMENT '카테고리 ID',
    DEFAULT_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '기본 카테고리 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50) NOT NULL,
    PRIMARY KEY (BOARD_CATEGORY_ID),
    UNIQUE KEY UK_BOARD_CAT (BOARD_ID, CATEGORY_ID),
    INDEX IDX_BOARD_CAT_BOARD (BOARD_ID),
    INDEX IDX_BOARD_CAT_CAT (CATEGORY_ID),
    CONSTRAINT FK_BOARD_CAT_BOARD FOREIGN KEY (BOARD_ID)
        REFERENCES TB_BOARD(BOARD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_BOARD_CAT_CATEGORY FOREIGN KEY (CATEGORY_ID)
        REFERENCES TB_CATEGORY(CATEGORY_ID) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT '보드-카테고리 매핑';

-- ============================================
-- 6. TB_BOARD_PROPERTY (보드-속성 매핑)
-- ============================================

CREATE TABLE IF NOT EXISTS TB_BOARD_PROPERTY (
    BOARD_PROPERTY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '매핑 ID',
    BOARD_ID BIGINT NOT NULL COMMENT '보드 ID',
    PROPERTY_ID BIGINT NOT NULL COMMENT '속성 ID',
    REQUIRED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '필수 여부 (보드 레벨)',
    VISIBLE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '표시 여부',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '표시 순서',
    DEFAULT_VALUE VARCHAR(500) NULL COMMENT '기본값 (카테고리에서 상속)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50) NOT NULL,
    PRIMARY KEY (BOARD_PROPERTY_ID),
    UNIQUE KEY UK_BOARD_PROP (BOARD_ID, PROPERTY_ID),
    INDEX IDX_BOARD_PROP_BOARD (BOARD_ID),
    INDEX IDX_BOARD_PROP_PROP (PROPERTY_ID),
    CONSTRAINT FK_BOARD_PROP_BOARD FOREIGN KEY (BOARD_ID)
        REFERENCES TB_BOARD(BOARD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_BOARD_PROP_PROPERTY FOREIGN KEY (PROPERTY_ID)
        REFERENCES TB_PROPERTY_DEF(PROPERTY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT '보드-속성 매핑 (보드에서 선택된 속성)';

-- ============================================
-- 7. TB_ITEM_PROPERTY_HISTORY (속성 변경 이력)
-- ============================================

CREATE TABLE IF NOT EXISTS TB_ITEM_PROPERTY_HISTORY (
    HISTORY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '이력 ID',
    ITEM_ID BIGINT NOT NULL COMMENT '업무 ID',
    PROPERTY_ID BIGINT NULL COMMENT '속성 ID (NULL이면 기본 속성)',
    PROPERTY_NAME VARCHAR(100) NOT NULL COMMENT '속성명 (스냅샷)',
    PROPERTY_TYPE VARCHAR(20) NOT NULL COMMENT '속성 타입',
    EVENT_TYPE VARCHAR(20) NOT NULL COMMENT 'CREATE, INITIAL, UPDATE, COMPLETE',
    OLD_VALUE_TEXT VARCHAR(1000) NULL COMMENT '이전 텍스트값',
    NEW_VALUE_TEXT VARCHAR(1000) NULL COMMENT '새 텍스트값',
    OLD_VALUE_DATE DATE NULL COMMENT '이전 날짜값',
    NEW_VALUE_DATE DATE NULL COMMENT '새 날짜값',
    OLD_VALUE_NUMBER DECIMAL(18,4) NULL COMMENT '이전 숫자값',
    NEW_VALUE_NUMBER DECIMAL(18,4) NULL COMMENT '새 숫자값',
    CHANGE_REASON VARCHAR(500) NULL COMMENT '변경 사유',
    CHANGED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일시',
    CHANGED_BY VARCHAR(50) NOT NULL COMMENT '변경자 USERNAME',
    PRIMARY KEY (HISTORY_ID),
    INDEX IDX_HIST_ITEM (ITEM_ID, CHANGED_AT),
    INDEX IDX_HIST_PROP (PROPERTY_ID),
    INDEX IDX_HIST_EVENT (EVENT_TYPE),
    CONSTRAINT FK_HIST_ITEM FOREIGN KEY (ITEM_ID)
        REFERENCES TB_ITEM(ITEM_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT '업무 속성 변경 이력';

-- ============================================
-- 8. TB_ITEM_SCORE (성과 점수)
-- ============================================

CREATE TABLE IF NOT EXISTS TB_ITEM_SCORE (
    SCORE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '점수 ID',
    ITEM_ID BIGINT NOT NULL COMMENT '업무 ID',

    -- 시간 기반 점수
    TIME_GRADE VARCHAR(20) NOT NULL COMMENT 'PERFECT, EXCELLENT, GREAT, GOOD, FAIR, POOR',
    TIME_SCORE DECIMAL(5,2) NOT NULL COMMENT '시간 기반 점수 (0~100)',
    COMPLETION_RATIO DECIMAL(5,4) NULL COMMENT '완료비율',

    -- 가중치
    DIFFICULTY_CODE VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' COMMENT 'LOW, MEDIUM, HIGH, EXTREME',
    DIFFICULTY_WEIGHT DECIMAL(3,2) NOT NULL DEFAULT 1.0 COMMENT '난이도 가중치',
    SCOPE_CODE VARCHAR(20) NOT NULL DEFAULT 'NONE' COMMENT 'NONE, MINOR, MAJOR, CHAOS',
    SCOPE_WEIGHT DECIMAL(3,2) NOT NULL DEFAULT 1.0 COMMENT '범위변경 가중치',
    RISK_CODE VARCHAR(20) NOT NULL DEFAULT 'NONE' COMMENT 'NONE, MITIGATED, CRITICAL',
    RISK_WEIGHT DECIMAL(3,2) NOT NULL DEFAULT 1.0 COMMENT '리스크 가중치',

    -- 최종 점수
    FINAL_SCORE DECIMAL(6,2) NOT NULL COMMENT '최종 점수',

    -- 계산 기준 날짜 (스냅샷)
    REQUEST_DATE DATE NULL COMMENT '요청일',
    START_DATE DATE NULL COMMENT '시작일',
    COMPLETION_DATE DATE NULL COMMENT '완료일',
    DUE_DATE DATE NULL COMMENT '마감일',
    ACTUAL_COMPLETION_AT DATETIME NULL COMMENT '실제 완료 처리일시',

    -- 승인 정보
    REQUIRES_APPROVAL CHAR(1) NOT NULL DEFAULT 'N' COMMENT '승인 필요 여부',
    APPROVED_YN CHAR(1) NULL COMMENT '승인 여부 (Y/N/NULL)',
    APPROVED_BY VARCHAR(50) NULL COMMENT '승인자 USERNAME',
    APPROVED_AT DATETIME NULL COMMENT '승인일시',

    -- 계산 정보
    CALCULATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '계산일시',
    CALCULATED_BY VARCHAR(50) NOT NULL COMMENT '계산자 USERNAME',

    PRIMARY KEY (SCORE_ID),
    UNIQUE KEY UK_ITEM_SCORE (ITEM_ID),
    INDEX IDX_SCORE_GRADE (TIME_GRADE),
    INDEX IDX_SCORE_CALC (CALCULATED_AT),
    INDEX IDX_SCORE_APPROVAL (REQUIRES_APPROVAL, APPROVED_YN),
    CONSTRAINT FK_SCORE_ITEM FOREIGN KEY (ITEM_ID)
        REFERENCES TB_ITEM(ITEM_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT '업무 성과 점수';

-- ============================================
-- 9. TB_ITEM에 CATEGORY_ID 참조 인덱스 확인
-- ============================================

-- TB_ITEM.CATEGORY_ID는 이미 존재하므로 인덱스만 확인
-- 없으면 생성
-- CREATE INDEX IF NOT EXISTS IDX_ITEM_CATEGORY ON TB_ITEM (CATEGORY_ID);
-- MySQL 5.7 이상에서는 IF NOT EXISTS 지원 안함, 무시하거나 별도 처리

-- ============================================
-- 완료 메시지
-- ============================================
SELECT 'TaskFlow 2.0 Schema Migration Completed' AS STATUS;
