-- ============================================
-- TaskFlow 2.0 Initial Data
-- Version: 2.0
-- Date: 2025-01-04
-- ============================================

-- ============================================
-- 1. 글로벌 속성 정의 (시스템 제공)
-- ============================================

-- 시작일 속성
INSERT INTO TB_PROPERTY_DEF (
    BOARD_ID, OWNER_TYPE, OWNER_USERNAME, OWNER_DEPT_CODE,
    PROPERTY_NAME, PROPERTY_TYPE, REQUIRED_YN, VISIBLE_YN, USE_YN, SORT_ORDER,
    CREATED_BY
) VALUES (
    NULL, 'GLOBAL', NULL, NULL,
    '시작일', 'DATE', 'N', 'Y', 'Y', 1,
    'system'
);

-- 완료일 속성
INSERT INTO TB_PROPERTY_DEF (
    BOARD_ID, OWNER_TYPE, OWNER_USERNAME, OWNER_DEPT_CODE,
    PROPERTY_NAME, PROPERTY_TYPE, REQUIRED_YN, VISIBLE_YN, USE_YN, SORT_ORDER,
    CREATED_BY
) VALUES (
    NULL, 'GLOBAL', NULL, NULL,
    '완료일', 'DATE', 'N', 'Y', 'Y', 2,
    'system'
);

-- 난이도 속성
INSERT INTO TB_PROPERTY_DEF (
    BOARD_ID, OWNER_TYPE, OWNER_USERNAME, OWNER_DEPT_CODE,
    PROPERTY_NAME, PROPERTY_TYPE, REQUIRED_YN, VISIBLE_YN, USE_YN, SORT_ORDER,
    CREATED_BY
) VALUES (
    NULL, 'GLOBAL', NULL, NULL,
    '난이도', 'SELECT', 'N', 'Y', 'Y', 3,
    'system'
);

-- 범위변경 속성
INSERT INTO TB_PROPERTY_DEF (
    BOARD_ID, OWNER_TYPE, OWNER_USERNAME, OWNER_DEPT_CODE,
    PROPERTY_NAME, PROPERTY_TYPE, REQUIRED_YN, VISIBLE_YN, USE_YN, SORT_ORDER,
    CREATED_BY
) VALUES (
    NULL, 'GLOBAL', NULL, NULL,
    '범위변경', 'SELECT', 'N', 'Y', 'Y', 4,
    'system'
);

-- 리스크대응 속성
INSERT INTO TB_PROPERTY_DEF (
    BOARD_ID, OWNER_TYPE, OWNER_USERNAME, OWNER_DEPT_CODE,
    PROPERTY_NAME, PROPERTY_TYPE, REQUIRED_YN, VISIBLE_YN, USE_YN, SORT_ORDER,
    CREATED_BY
) VALUES (
    NULL, 'GLOBAL', NULL, NULL,
    '리스크대응', 'SELECT', 'N', 'Y', 'Y', 5,
    'system'
);

-- ============================================
-- 2. 난이도 옵션
-- ============================================

INSERT INTO TB_PROPERTY_OPTION (PROPERTY_ID, OPTION_VALUE, OPTION_LABEL, COLOR, SORT_ORDER, USE_YN, CREATED_BY)
SELECT PROPERTY_ID, 'LOW', 'Low (반복작업)', '#22C55E', 1, 'Y', 'system'
FROM TB_PROPERTY_DEF WHERE PROPERTY_NAME = '난이도' AND OWNER_TYPE = 'GLOBAL';

INSERT INTO TB_PROPERTY_OPTION (PROPERTY_ID, OPTION_VALUE, OPTION_LABEL, COLOR, SORT_ORDER, USE_YN, CREATED_BY)
SELECT PROPERTY_ID, 'MEDIUM', 'Medium (일반)', '#3B82F6', 2, 'Y', 'system'
FROM TB_PROPERTY_DEF WHERE PROPERTY_NAME = '난이도' AND OWNER_TYPE = 'GLOBAL';

INSERT INTO TB_PROPERTY_OPTION (PROPERTY_ID, OPTION_VALUE, OPTION_LABEL, COLOR, SORT_ORDER, USE_YN, CREATED_BY)
SELECT PROPERTY_ID, 'HIGH', 'High (높음)', '#F59E0B', 3, 'Y', 'system'
FROM TB_PROPERTY_DEF WHERE PROPERTY_NAME = '난이도' AND OWNER_TYPE = 'GLOBAL';

INSERT INTO TB_PROPERTY_OPTION (PROPERTY_ID, OPTION_VALUE, OPTION_LABEL, COLOR, SORT_ORDER, USE_YN, CREATED_BY)
SELECT PROPERTY_ID, 'EXTREME', 'Extreme (어려움)', '#EF4444', 4, 'Y', 'system'
FROM TB_PROPERTY_DEF WHERE PROPERTY_NAME = '난이도' AND OWNER_TYPE = 'GLOBAL';

-- ============================================
-- 3. 범위변경 옵션
-- ============================================

INSERT INTO TB_PROPERTY_OPTION (PROPERTY_ID, OPTION_VALUE, OPTION_LABEL, COLOR, SORT_ORDER, USE_YN, CREATED_BY)
SELECT PROPERTY_ID, 'NONE', 'None (변경없음)', '#6B7280', 1, 'Y', 'system'
FROM TB_PROPERTY_DEF WHERE PROPERTY_NAME = '범위변경' AND OWNER_TYPE = 'GLOBAL';

INSERT INTO TB_PROPERTY_OPTION (PROPERTY_ID, OPTION_VALUE, OPTION_LABEL, COLOR, SORT_ORDER, USE_YN, CREATED_BY)
SELECT PROPERTY_ID, 'MINOR', 'Minor (20%이내)', '#22C55E', 2, 'Y', 'system'
FROM TB_PROPERTY_DEF WHERE PROPERTY_NAME = '범위변경' AND OWNER_TYPE = 'GLOBAL';

INSERT INTO TB_PROPERTY_OPTION (PROPERTY_ID, OPTION_VALUE, OPTION_LABEL, COLOR, SORT_ORDER, USE_YN, CREATED_BY)
SELECT PROPERTY_ID, 'MAJOR', 'Major (30%이상)', '#F59E0B', 3, 'Y', 'system'
FROM TB_PROPERTY_DEF WHERE PROPERTY_NAME = '범위변경' AND OWNER_TYPE = 'GLOBAL';

INSERT INTO TB_PROPERTY_OPTION (PROPERTY_ID, OPTION_VALUE, OPTION_LABEL, COLOR, SORT_ORDER, USE_YN, CREATED_BY)
SELECT PROPERTY_ID, 'CHAOS', 'Chaos (엎어짐)', '#EF4444', 4, 'Y', 'system'
FROM TB_PROPERTY_DEF WHERE PROPERTY_NAME = '범위변경' AND OWNER_TYPE = 'GLOBAL';

-- ============================================
-- 4. 리스크대응 옵션
-- ============================================

INSERT INTO TB_PROPERTY_OPTION (PROPERTY_ID, OPTION_VALUE, OPTION_LABEL, COLOR, SORT_ORDER, USE_YN, CREATED_BY)
SELECT PROPERTY_ID, 'NONE', 'None (이슈없음)', '#6B7280', 1, 'Y', 'system'
FROM TB_PROPERTY_DEF WHERE PROPERTY_NAME = '리스크대응' AND OWNER_TYPE = 'GLOBAL';

INSERT INTO TB_PROPERTY_OPTION (PROPERTY_ID, OPTION_VALUE, OPTION_LABEL, COLOR, SORT_ORDER, USE_YN, CREATED_BY)
SELECT PROPERTY_ID, 'MITIGATED', 'Mitigated (이슈해결)', '#3B82F6', 2, 'Y', 'system'
FROM TB_PROPERTY_DEF WHERE PROPERTY_NAME = '리스크대응' AND OWNER_TYPE = 'GLOBAL';

INSERT INTO TB_PROPERTY_OPTION (PROPERTY_ID, OPTION_VALUE, OPTION_LABEL, COLOR, SORT_ORDER, USE_YN, CREATED_BY)
SELECT PROPERTY_ID, 'CRITICAL', 'Critical (실패복구)', '#EF4444', 3, 'Y', 'system'
FROM TB_PROPERTY_DEF WHERE PROPERTY_NAME = '리스크대응' AND OWNER_TYPE = 'GLOBAL';

-- ============================================
-- 완료 메시지
-- ============================================
SELECT 'TaskFlow 2.0 Initial Data Inserted' AS STATUS;
