-- ============================================
-- 템플릿 카테고리/속성 기능 추가
-- Version: 2.0.5
-- ============================================

-- 1. TB_TASK_TEMPLATE에 카테고리 컬럼 추가
ALTER TABLE TB_TASK_TEMPLATE
ADD COLUMN CATEGORY_ID BIGINT NULL COMMENT '기본 카테고리 ID' AFTER DEFAULT_ITEM_STATUS;

-- 인덱스 추가
CREATE INDEX IDX_TPL_CATEGORY ON TB_TASK_TEMPLATE (CATEGORY_ID);

-- 2. TB_TEMPLATE_PROPERTY 테이블 생성 (템플릿-속성 매핑)
CREATE TABLE TB_TEMPLATE_PROPERTY (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '매핑 ID',
    TEMPLATE_ID BIGINT NOT NULL COMMENT '템플릿 ID',
    PROPERTY_ID BIGINT NOT NULL COMMENT '속성 ID',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    DEFAULT_VALUE VARCHAR(500) NULL COMMENT '기본값',
    REQUIRED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '필수 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시 (논리삭제)',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_TEMPLATE_PROPERTY (TEMPLATE_ID, PROPERTY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='템플릿 속성 매핑';

-- 인덱스
CREATE INDEX IDX_TP_TEMPLATE ON TB_TEMPLATE_PROPERTY (TEMPLATE_ID);
CREATE INDEX IDX_TP_PROPERTY ON TB_TEMPLATE_PROPERTY (PROPERTY_ID);
