-- ==============================================
-- 작업 템플릿 OWNER_TYPE 지원 마이그레이션
-- 버전: 2.0.6
-- 설명: 템플릿에 글로벌/매니저/개인 소유 유형 추가
-- ==============================================

-- 1. TB_TASK_TEMPLATE에 OWNER_TYPE 관련 컬럼 추가
ALTER TABLE TB_TASK_TEMPLATE
ADD COLUMN OWNER_TYPE VARCHAR(20) NOT NULL DEFAULT 'USER' COMMENT '소유 유형 (GLOBAL, MANAGER, USER)' AFTER CATEGORY_ID,
ADD COLUMN OWNER_USERNAME VARCHAR(50) NULL COMMENT '소유자 USERNAME' AFTER OWNER_TYPE,
ADD COLUMN OWNER_DEPT_CODE VARCHAR(50) NULL COMMENT '소유자 부서코드 (MANAGER용)' AFTER OWNER_USERNAME;

-- 2. 인덱스 추가
CREATE INDEX IDX_TPL_OWNER ON TB_TASK_TEMPLATE (OWNER_TYPE, OWNER_USERNAME);
CREATE INDEX IDX_TPL_DEPT ON TB_TASK_TEMPLATE (OWNER_DEPT_CODE);

-- 3. 기존 데이터 마이그레이션 (기존 템플릿은 생성자 기준 USER로)
UPDATE TB_TASK_TEMPLATE
SET OWNER_TYPE = 'USER',
    OWNER_USERNAME = CREATED_BY
WHERE OWNER_USERNAME IS NULL;
