-- =============================================
-- 외부 DB 연결 및 쿼리 기능 마이그레이션
-- 버전: 2.1
-- 날짜: 2025-01-12
-- 설명: 속성에서 외부 DB 쿼리 결과를 동적 옵션으로 사용
-- =============================================

-- =============================================
-- 1. TB_EXTERNAL_DATASOURCE (외부 DB 연결 정보)
-- =============================================
CREATE TABLE IF NOT EXISTS TB_EXTERNAL_DATASOURCE (
    DATASOURCE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '데이터소스 ID',
    DATASOURCE_CODE VARCHAR(50) NOT NULL COMMENT '고유 코드',
    DATASOURCE_NAME VARCHAR(100) NOT NULL COMMENT '표시 이름',
    DB_TYPE VARCHAR(20) NOT NULL COMMENT 'DB 타입 (MYSQL/ORACLE/MSSQL/TIBERO)',
    CONNECTION_TYPE VARCHAR(20) NULL DEFAULT 'SERVICE_NAME' COMMENT '연결 타입 (Oracle: SID/SERVICE_NAME)',
    HOST VARCHAR(255) NOT NULL COMMENT '호스트 주소',
    PORT INT NOT NULL COMMENT '포트 번호',
    DATABASE_NAME VARCHAR(100) NOT NULL COMMENT '데이터베이스명',
    SCHEMA_NAME VARCHAR(100) NULL COMMENT '스키마명 (선택적, 문서화 용도)',
    USERNAME VARCHAR(100) NOT NULL COMMENT '접속 계정',
    PASSWORD_ENCRYPTED VARCHAR(500) NOT NULL COMMENT 'AES-256 암호화 비밀번호',
    CONNECTION_TIMEOUT INT NOT NULL DEFAULT 5000 COMMENT '연결 타임아웃 (ms)',
    QUERY_TIMEOUT INT NOT NULL DEFAULT 30000 COMMENT '쿼리 타임아웃 (ms)',
    MAX_POOL_SIZE INT NOT NULL DEFAULT 3 COMMENT '최대 풀 크기',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (DATASOURCE_ID),
    CONSTRAINT UK_EDS_CODE UNIQUE (DATASOURCE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='외부 DB 연결 정보';

-- 인덱스
CREATE INDEX IDX_EDS_USE ON TB_EXTERNAL_DATASOURCE (USE_YN);
CREATE INDEX IDX_EDS_TYPE ON TB_EXTERNAL_DATASOURCE (DB_TYPE);

-- =============================================
-- 2. TB_EXTERNAL_QUERY (외부 쿼리 정의)
-- =============================================
CREATE TABLE IF NOT EXISTS TB_EXTERNAL_QUERY (
    QUERY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '쿼리 ID',
    DATASOURCE_ID BIGINT NOT NULL COMMENT 'FK -> TB_EXTERNAL_DATASOURCE',
    QUERY_CODE VARCHAR(50) NOT NULL COMMENT '쿼리 고유 코드',
    QUERY_NAME VARCHAR(100) NOT NULL COMMENT '쿼리 표시명',
    DESCRIPTION VARCHAR(500) NULL COMMENT '쿼리 설명',
    QUERY_SQL TEXT NOT NULL COMMENT 'SELECT 쿼리문',
    OWNER_TYPE VARCHAR(20) NOT NULL DEFAULT 'USER' COMMENT '소유 유형 (GLOBAL/MANAGER/USER)',
    OWNER_USERNAME VARCHAR(50) NULL COMMENT '소유자 USERNAME',
    OWNER_DEPT_CODE VARCHAR(20) NULL COMMENT '소유자 부서 코드',
    VALUE_COLUMN VARCHAR(100) NOT NULL DEFAULT 'value' COMMENT '값 컬럼명',
    LABEL_COLUMN VARCHAR(100) NOT NULL DEFAULT 'label' COMMENT '라벨 컬럼명',
    COLOR_COLUMN VARCHAR(100) NULL COMMENT '색상 컬럼명',
    CACHE_ENABLED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '캐시 사용 여부',
    CACHE_TTL_SECONDS INT NULL DEFAULT 300 COMMENT '캐시 TTL (초)',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    LAST_EXECUTED_AT DATETIME NULL COMMENT '마지막 실행 시간',
    LAST_RESULT_COUNT INT NULL COMMENT '마지막 결과 건수',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자 USERNAME',
    DELETED_AT DATETIME NULL COMMENT '삭제일시',
    DELETED_BY VARCHAR(50) NULL COMMENT '삭제자 USERNAME',
    PRIMARY KEY (QUERY_ID),
    CONSTRAINT UK_EQ_CODE UNIQUE (QUERY_CODE),
    CONSTRAINT FK_EQ_DATASOURCE FOREIGN KEY (DATASOURCE_ID)
        REFERENCES TB_EXTERNAL_DATASOURCE (DATASOURCE_ID) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='외부 쿼리 정의';

-- 인덱스
CREATE INDEX IDX_EQ_DATASOURCE ON TB_EXTERNAL_QUERY (DATASOURCE_ID);
CREATE INDEX IDX_EQ_OWNER_TYPE ON TB_EXTERNAL_QUERY (OWNER_TYPE);
CREATE INDEX IDX_EQ_OWNER_USER ON TB_EXTERNAL_QUERY (OWNER_USERNAME);
CREATE INDEX IDX_EQ_USE ON TB_EXTERNAL_QUERY (USE_YN);

-- =============================================
-- 3. TB_PROPERTY_DEF 컬럼 추가 (기존 테이블 수정)
-- =============================================

-- 외부 쿼리 ID 컬럼 추가
ALTER TABLE TB_PROPERTY_DEF
ADD COLUMN IF NOT EXISTS EXTERNAL_QUERY_ID BIGINT NULL COMMENT 'FK -> TB_EXTERNAL_QUERY' AFTER BOARD_ID;

-- 데이터 소스 타입 컬럼 추가
ALTER TABLE TB_PROPERTY_DEF
ADD COLUMN IF NOT EXISTS DATA_SOURCE_TYPE VARCHAR(20) NOT NULL DEFAULT 'INTERNAL' COMMENT '데이터 소스 타입 (INTERNAL/EXTERNAL)' AFTER EXTERNAL_QUERY_ID;

-- FK 제약조건 추가
ALTER TABLE TB_PROPERTY_DEF
ADD CONSTRAINT FK_PD_EXTERNAL_QUERY FOREIGN KEY (EXTERNAL_QUERY_ID)
    REFERENCES TB_EXTERNAL_QUERY (QUERY_ID) ON DELETE SET NULL;

-- 인덱스 추가
CREATE INDEX IDX_PD_EXTERNAL_QUERY ON TB_PROPERTY_DEF (EXTERNAL_QUERY_ID);
CREATE INDEX IDX_PD_DATA_SOURCE_TYPE ON TB_PROPERTY_DEF (DATA_SOURCE_TYPE);

-- =============================================
-- 완료 메시지
-- =============================================
SELECT 'External DataSource Migration completed successfully!' AS Message;
