-- =============================================
-- TB_ITEM_CONTENT: 업무 상세 내용
-- 업무(Item)의 리치 텍스트 내용을 별도 테이블로 분리
-- =============================================

CREATE TABLE IF NOT EXISTS TB_ITEM_CONTENT (
    CONTENT_ID      BIGINT          NOT NULL AUTO_INCREMENT COMMENT '컨텐츠 ID',
    ITEM_ID         BIGINT          NOT NULL COMMENT '업무 ID (FK → TB_ITEM)',
    CONTENT_TYPE    VARCHAR(20)     NOT NULL DEFAULT 'HTML' COMMENT '컨텐츠 타입 (HTML, JSON, MARKDOWN)',
    CONTENT         MEDIUMTEXT      NULL COMMENT '컨텐츠 본문 (리치 텍스트)',
    PLAIN_TEXT      TEXT            NULL COMMENT '검색용 평문 텍스트',
    VERSION         INT             NOT NULL DEFAULT 1 COMMENT '버전 (동시 편집 충돌 방지)',
    CREATED_AT      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY      VARCHAR(50)     NOT NULL COMMENT '생성자 USERNAME',
    UPDATED_AT      DATETIME        NULL ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY      VARCHAR(50)     NULL COMMENT '수정자 USERNAME',
    PRIMARY KEY (CONTENT_ID),
    UNIQUE KEY UK_ITEM_CONTENT (ITEM_ID),
    CONSTRAINT FK_ITEM_CONTENT_ITEM
        FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM(ITEM_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='업무 상세 내용';

-- 검색용 FULLTEXT 인덱스
CREATE FULLTEXT INDEX FT_ITEM_CONTENT_PLAIN ON TB_ITEM_CONTENT(PLAIN_TEXT);

-- TB_ITEM.DESCRIPTION 컬럼 주석 업데이트 (용도 명확화)
ALTER TABLE TB_ITEM MODIFY COLUMN DESCRIPTION VARCHAR(500) NULL COMMENT '업무 설명 (요약)';
