-- ============================================
-- TaskFlow DB Schema Migration Script
-- 작성일: 2025-12-16
-- 목적: DB-Backend 불일치 해결을 위한 스키마 확장
-- ============================================

-- ============================================
-- 1. TB_BOARD 확장
-- ============================================
-- 추가 컬럼: DEFAULT_VIEW, COLOR, SORT_ORDER

ALTER TABLE TB_BOARD
ADD COLUMN DEFAULT_VIEW VARCHAR(20) DEFAULT 'TABLE'
COMMENT '기본 뷰 타입 (TABLE/KANBAN/LIST)'
AFTER OWNER_ID;

ALTER TABLE TB_BOARD
ADD COLUMN COLOR VARCHAR(7) NULL
COMMENT '보드 색상 (#RRGGBB)'
AFTER DEFAULT_VIEW;

ALTER TABLE TB_BOARD
ADD COLUMN SORT_ORDER INT NOT NULL DEFAULT 0
COMMENT '정렬 순서'
AFTER COLOR;

-- ============================================
-- 2. TB_PROPERTY_DEF 확장
-- ============================================
-- 추가 컬럼: PROPERTY_CODE, DEFAULT_VALUE, SYSTEM_YN, USE_YN

ALTER TABLE TB_PROPERTY_DEF
ADD COLUMN PROPERTY_CODE VARCHAR(50) NOT NULL DEFAULT ''
COMMENT '속성 코드'
AFTER PROPERTY_NAME;

ALTER TABLE TB_PROPERTY_DEF
ADD COLUMN DEFAULT_VALUE VARCHAR(500) NULL
COMMENT '기본값'
AFTER REQUIRED_YN;

ALTER TABLE TB_PROPERTY_DEF
ADD COLUMN SYSTEM_YN CHAR(1) NOT NULL DEFAULT 'N'
COMMENT '시스템 속성 여부 (Y/N)'
AFTER SORT_ORDER;

ALTER TABLE TB_PROPERTY_DEF
ADD COLUMN USE_YN CHAR(1) NOT NULL DEFAULT 'Y'
COMMENT '사용 여부 (Y/N)'
AFTER SYSTEM_YN;

-- 기존 데이터의 PROPERTY_CODE 기본값 설정
UPDATE TB_PROPERTY_DEF
SET PROPERTY_CODE = CONCAT('PROP_', PROPERTY_ID)
WHERE PROPERTY_CODE = '';

-- ============================================
-- 3. TB_PROPERTY_OPTION 확장
-- ============================================
-- 추가 컬럼: OPTION_CODE

ALTER TABLE TB_PROPERTY_OPTION
ADD COLUMN OPTION_CODE VARCHAR(50) NULL
COMMENT '옵션 코드'
AFTER PROPERTY_ID;

-- ============================================
-- 4. TB_ITEM 확장
-- ============================================
-- 추가 컬럼: TITLE, PREVIOUS_STATUS, SORT_ORDER, DUE_DATE,
--           COMPLETED_AT, COMPLETED_BY, DELETED_BY

ALTER TABLE TB_ITEM
ADD COLUMN TITLE VARCHAR(200) NULL
COMMENT '업무 제목'
AFTER BOARD_ID;

ALTER TABLE TB_ITEM
ADD COLUMN PREVIOUS_STATUS VARCHAR(20) NULL
COMMENT '삭제 전 상태 (복원용)'
AFTER STATUS;

ALTER TABLE TB_ITEM
ADD COLUMN SORT_ORDER INT NOT NULL DEFAULT 0
COMMENT '정렬 순서'
AFTER ASSIGNEE_ID;

ALTER TABLE TB_ITEM
ADD COLUMN DUE_DATE DATE NULL
COMMENT '마감일'
AFTER END_TIME;

ALTER TABLE TB_ITEM
ADD COLUMN COMPLETED_AT DATETIME NULL
COMMENT '완료 시간'
AFTER DUE_DATE;

ALTER TABLE TB_ITEM
ADD COLUMN COMPLETED_BY BIGINT NULL
COMMENT '완료 처리자 ID'
AFTER COMPLETED_AT;

ALTER TABLE TB_ITEM
ADD COLUMN DELETED_BY BIGINT NULL
COMMENT '삭제 처리자 ID'
AFTER DELETED_AT;

-- FK 제약 조건 추가 (선택사항)
-- ALTER TABLE TB_ITEM
-- ADD CONSTRAINT FK_ITEM_COMPLETED_BY
-- FOREIGN KEY (COMPLETED_BY) REFERENCES TB_USER (USER_ID)
-- ON DELETE SET NULL ON UPDATE CASCADE;

-- ALTER TABLE TB_ITEM
-- ADD CONSTRAINT FK_ITEM_DELETED_BY
-- FOREIGN KEY (DELETED_BY) REFERENCES TB_USER (USER_ID)
-- ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================
-- 5. 인덱스 추가 (성능 최적화)
-- ============================================

-- TB_ITEM 인덱스
CREATE INDEX IDX_ITEM_SORT ON TB_ITEM (BOARD_ID, SORT_ORDER);
CREATE INDEX IDX_ITEM_DUE_DATE ON TB_ITEM (DUE_DATE);
CREATE INDEX IDX_ITEM_COMPLETED ON TB_ITEM (COMPLETED_AT);

-- TB_PROPERTY_DEF 인덱스
CREATE INDEX IDX_PROPERTY_DEF_CODE ON TB_PROPERTY_DEF (BOARD_ID, PROPERTY_CODE);
CREATE INDEX IDX_PROPERTY_DEF_USE ON TB_PROPERTY_DEF (BOARD_ID, USE_YN);

-- TB_BOARD 인덱스
CREATE INDEX IDX_BOARD_SORT ON TB_BOARD (OWNER_ID, SORT_ORDER);

-- ============================================
-- 6. 초기 데이터 마이그레이션
-- ============================================

-- 기존 아이템의 TITLE을 CONTENT에서 추출 (필요시)
-- UPDATE TB_ITEM SET TITLE = LEFT(CONTENT, 200) WHERE TITLE IS NULL;

-- ============================================
-- 완료
-- ============================================
-- 이 스크립트 실행 후 Mapper XML 수정이 필요합니다.
-- 참조: DB_BACKEND_MISMATCH_REPORT.md
